dxscale/core/serviceBase/events/Service_Invoke_Event__e/objects/Service_Invoke_Event__e/Service_Invoke_Event__e.object-meta.xml
<CustomObject>
    <label>Service Inbound Event</label>
    <pluralLabel>Service Inbound Events</pluralLabel>
</CustomObject>

dxscale/core/serviceBase/events/Service_Invoke_Event__e/objects/Service_Invoke_Event__e/fields/InputData__c.field-meta.xml
<CustomField>
    <fullName>InputData__c</fullName>
    <description>Service input data - likely to be a serialised JSON string. See Service Framework for valid input interfaces</description>
    <label>Args</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/serviceBase/events/Service_Invoke_Event__e/objects/Service_Invoke_Event__e/fields/InvocationDetails__c.field-meta.xml
<CustomField>
    <fullName>InvocationDetails__c</fullName>
    <description>JSON serialized details of the invocation</description>
    <label>InvokerDetails</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/serviceBase/events/classes/Service_Invoke_Event_TriggerHandler_Test.cls
@isTest
public class Service_Invoke_Event_TriggerHandler_Test {
    


    @isTest
    static void testPublish(){

        Service_Invoke_Event__e event = new Service_Invoke_Event__e();
        event.InputData__c = 'some input load';
        event.InvocationDetails__c = 'some invocation JSON';
        Service_Invoke_Event_TriggerHandler handler = new Service_Invoke_Event_TriggerHandler();
        handler.setTriggerData(new List<SObject>{event},null,null);

        Test.startTest();
            try{
                handler.call('onAfterInsert', null);
            }catch(Exception e){
                // as this is testing the handler (not he bus) all we can assert is it didn't fail
                System.assertEquals(true, false,'Should not have thrown an error, force failure');
            }
            
        Test.stopTest();
    }


}