dxscale/core/serviceBase/objects/Service_Implementation__mdt/Service_Implementation__mdt.object-meta.xml
<CustomObject>
    <description>Configures the correct implementation of a Service / Service Method by providing a concrete Apex class or Flow to provide the implementation</description>
    <label>Service Implementation</label>
    <pluralLabel>Service Implementations</pluralLabel>
</CustomObject>

dxscale/core/serviceBase/objects/Service_Invocation__mdt/Service_Invocation__mdt.object-meta.xml
<CustomObject>
    <label>Service Invocation</label>
    <pluralLabel>Service Invocations</pluralLabel>
</CustomObject>

dxscale/core/serviceBase/objects/Service_Invocation__mdt/fields/Iteration__c.field-meta.xml
<CustomField>
    <fullName>Iteration__c</fullName>
    <description>a versioning iterated number for a Service. This is only required for a Services with Methods as implementation versioning is provided by Service Versions otherwise.</description>
    <inlineHelpText>a versioning iterated number for a Service. This is only required for a Services with Methods as implementation versioning is provided by Service Versions otherwise.</inlineHelpText>
    <label>Iteration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Invocation__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>a business logical name for the method. Name for the method must match between &quot;Service Invocation&quot; and &quot;Service Method&quot;</description>
    <inlineHelpText>a business logical name for the method. Name for the method must match between &quot;Service Invocation&quot; and &quot;Service Method&quot;</inlineHelpText>
    <label>Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/Service_Method__mdt.object-meta.xml
<CustomObject>
    <description>The Service Method CMT relates business method names and the Service record we’ve just identified to Service Versions</description>
    <label>Service Method</label>
    <pluralLabel>Service Methods</pluralLabel>
</CustomObject>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/External_Processing_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Processing_Id__c</fullName>
    <description>An id to help an external process a request. Only used for Remote Proxy Services.
For a Salesforce remote this is the Invocation Id on a remote system that invokes a service on that remote system.</description>
    <inlineHelpText>An id to help an external process a request. Only used for Remote Proxy Services.
For a Salesforce remote this is the Invocation Id on a remote system that invokes a service on that remote system.</inlineHelpText>
    <label>External Processing Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/How_Implemented__c.field-meta.xml
<CustomField>
    <fullName>How_Implemented__c</fullName>
    <description>How the Method is implemented. If &quot;Implementation&quot; then we need a related Service Implementation record</description>
    <inlineHelpText>How the Method is implemented. If &quot;Implementation&quot; then we need a related Service Implementation record</inlineHelpText>
    <label>How Implemented</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Implementation</fullName>
                <default>true</default>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>PassThrough</fullName>
            </value>
            <value>
                <fullName>Chain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/Iteration__c.field-meta.xml
<CustomField>
    <fullName>Iteration__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Iteration of the Service that this Service Method is application to</description>
    <inlineHelpText>Iteration of the Service that this Service Method is application to</inlineHelpText>
    <label>Iteration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>a business logical name for the method. Name for the method must match between &quot;Service Invocation&quot; and &quot;Service Method&quot;</description>
    <inlineHelpText>a business logical name for the method. Name for the method must match between &quot;Service Invocation&quot; and &quot;Service Method&quot;</inlineHelpText>
    <label>Method</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/Next_Invocation__c.field-meta.xml
<CustomField>
    <fullName>Next_Invocation__c</fullName>
    <description>If this is part of a chain of invocations this points to the next invocation to call after this has completed</description>
    <inlineHelpText>If this is part of a chain of invocations this points to the next invocation to call after this has completed</inlineHelpText>
    <label>Next Invocation</label>
    <referenceTo>Service_Invocation__mdt</referenceTo>
    <relationshipLabel>Called by Chained Methods</relationshipLabel>
    <relationshipName>Called_By_Chained_Methods</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/Response_Invocation__c.field-meta.xml
<CustomField>
    <fullName>Response_Invocation__c</fullName>
    <description>If this is part of a chain of invocations this points to an invocation to call to process a response to the Next Invocation</description>
    <inlineHelpText>If this is part of a chain of invocations this points to an invocation to call to process a response to the Next Invocation</inlineHelpText>
    <label>Response Invocation</label>
    <referenceTo>Service_Invocation__mdt</referenceTo>
    <relationshipLabel>Called by Chained Response Methods</relationshipLabel>
    <relationshipName>Called_By_Chained_Response_Methods</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>lookup to Service CMT</description>
    <inlineHelpText>lookup to Service CMT</inlineHelpText>
    <label>Service</label>
    <referenceTo>Service__mdt</referenceTo>
    <relationshipLabel>Service Methods</relationshipLabel>
    <relationshipName>Service_Methods</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Method__mdt/fields/Service_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Service_Implementation__c</fullName>
    <description>Lookup to the Service Implementation MDT</description>
    <inlineHelpText>Lookup to the Service Implementation MDT</inlineHelpText>
    <label>Service Implementation</label>
    <referenceTo>Service_Implementation__mdt</referenceTo>
    <relationshipLabel>Service Methods</relationshipLabel>
    <relationshipName>Service_Methods</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/serviceBase/classes/ServiceMethod.cls
public inherited sharing class ServiceMethod {

    /* Custom Metadata Retrieval and Cacheing */

    private static Map<String,ServiceMethod.ServiceMethodWrap> mapServiceMethodWrap = new Map<String,ServiceMethod.ServiceMethodWrap>(); 

    public class ServiceMethodWrap {
        public Id serviceMethodMetadataId;
        public String serviceName;
        public Integer iteration;
        public String serviceMethodName;
        public String serviceImplementationName;
        public String nextInvocationName;
        public String responseInvocationName;
        public Service_Method__mdt serviceMethodMDT;

        public String getServiceImplementationName() {
            return this.serviceImplementationName;
        }

        public String getNextInvocationName() {
            return this.nextInvocationName;
        }

        public String getResponseInvocationName() {
            return this.responseInvocationName;
        }

        public String getServiceMethodMetadataId() {
            return this.serviceMethodMetadataId;
        }

    }

    public static String createServiceMetadataKey (String serviceName, Integer iteration, String serviceMethodName) {
        return serviceName + '.' + iteration + '.' + serviceMethodName;
    }

    public static ServiceMethod.ServiceMethodWrap getMetadataWrap (String serviceName, Integer iteration, String serviceMethodName) {
        String mapKey = createServiceMetadataKey (serviceName, iteration, serviceMethodName);
        if (mapServiceMethodWrap.containsKey(mapKey)) {
            return mapServiceMethodWrap.get(mapKey);
        }
        else {
            System.debug('ServiceMethod.getMetadataWrap:' + serviceName + ',' +  iteration + ',' + serviceMethodName);

            List<Service_Method__mdt> listServiceMethodMDT = 
                [SELECT Id, DeveloperName,Method__c,Service__c, Service_Implementation__c, Iteration__c, How_Implemented__c, External_Processing_Id__c, Next_Invocation__r.DeveloperName,Response_Invocation__r.DeveloperName, Service_Implementation__r.DeveloperName, Service__r.DeveloperName 
                    from Service_Method__mdt
                    where Method__c = :serviceMethodName and Iteration__c = :iteration and Service__r.DeveloperName = :serviceName];
            
            if (listServiceMethodMDT.size() > 0) {
                ServiceMethod.ServiceMethodWrap smw = cacheMetadata(serviceName, iteration, serviceMethodName, listServiceMethodMDT[0]);
                smw.serviceImplementationName = listServiceMethodMDT[0].Service_Implementation__r.DeveloperName;
                smw.nextInvocationName = listServiceMethodMDT[0].Next_Invocation__r.DeveloperName;
                smw.responseInvocationName = listServiceMethodMDT[0].Response_Invocation__r.DeveloperName;
                smw.serviceMethodMetadataId = listServiceMethodMDT[0].Id;
                return smw;
            }
            else {
                return null;
            }
        }
    }

    public static ServiceMethod.ServiceMethodWrap cacheMetadata(String serviceName, Integer iteration, String serviceMethodName, Service_Method__mdt newServiceMethodMDT) {
        ServiceMethod.ServiceMethodWrap smw = new ServiceMethod.ServiceMethodWrap();
        String mapKey = createServiceMetadataKey (serviceName, iteration, serviceMethodName);
        smw.serviceName = serviceName;
        smw.iteration = iteration;
        smw.serviceMethodName = serviceMethodName;
        smw.serviceMethodMDT = newServiceMethodMDT;
        mapServiceMethodWrap.put(mapKey,smw);
        return smw;
    }

    // For test classes only, creates dummy custom metadata
    // instantiate a mininmal CMT record  
    // Add additional attributes to the variable returned and add to the CMT map.

    public static Service_Method__mdt createTestMetadata(String serviceName, Integer iteration, String serviceMethodName) {
        Service_Method__mdt serviceMethodMDT = new Service_Method__mdt();
        serviceMethodMDT.DeveloperName = createServiceMetadataKey (serviceName, iteration, serviceMethodName);
        serviceMethodMDT.Method__c = serviceMethodName;
        return serviceMethodMDT;
    }

}