dxscale/core/serviceBase/objects/Service_Implementation__mdt/Service_Implementation__mdt.object-meta.xml
<CustomObject>
    <description>Configures the correct implementation of a Service / Service Method by providing a concrete Apex class or Flow to provide the implementation</description>
    <label>Service Implementation</label>
    <pluralLabel>Service Implementations</pluralLabel>
</CustomObject>

dxscale/core/serviceBase/objects/Service_Implementation__mdt/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <description>States how which technology provides the implementation</description>
    <inlineHelpText>States how which technology provides the implementation</inlineHelpText>
    <label>Implementation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ApexClass</fullName>
                <default>true</default>
                <label>ApexClass</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>RemoteInvocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/core/serviceBase/objects/Service_Implementation__mdt/fields/Implementing_Class__c.field-meta.xml
<CustomField>
    <fullName>Implementing_Class__c</fullName>
    <description>Class that implements the service for implementation with Implementation Type "ApexClass"</description>
    <inlineHelpText>Class that implements the service for implementation with Implementation Type "ApexClass"</inlineHelpText>
    <label>Implementing Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Implementation__mdt/fields/Implementing_Flow__c.field-meta.xml
<CustomField>
    <fullName>Implementing_Flow__c</fullName>
    <description>Name of the implementing flow</description>
    <inlineHelpText>Name of the implementing flow</inlineHelpText>
    <label>Implementing Flow</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Implementation__mdt/fields/Output_Creation_Class__c.field-meta.xml
<CustomField>
    <fullName>Output_Creation_Class__c</fullName>
    <description>The class used to implement the Output Interface Version. This is optional for Apex Implementations but mandatory for Flow Implementations (in which case it must implement IService_Flow_Output)</description>
    <inlineHelpText>The class used to implement the Output Interface Version. This is optional for Apex Implementations but mandatory for Flow Implementations (in which case it must implement IService_Flow_Output)</inlineHelpText>
    <label>Output Creation Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/classes/ServiceImplementation.cls
public inherited sharing class ServiceImplementation {

    /* Custom Metadata Retrieval and Cacheing */

    private static Map<String,ServiceImplementation.ServiceImplementationWrap> mapServiceImplementationWrap = new Map<String,ServiceImplementation.ServiceImplementationWrap>(); 

    public class ServiceImplementationWrap {
        public Id serviceImplementationMetadataId;
        public String serviceImplementationName;
        public Service_Implementation__mdt serviceImplementationMDT;

        public String getServiceImplementationMetadataId() {
            return this.serviceImplementationMetadataId;
        }

    }

    public static ServiceImplementation.ServiceImplementationWrap getMetadataWrap (String serviceImplementationName) {
        if (mapServiceImplementationWrap.containsKey(serviceImplementationName)) {
            return mapServiceImplementationWrap.get(serviceImplementationName);
        }
        else {

            List<Service_Implementation__mdt> listServiceImplementationMDT = 
                [SELECT Id, DeveloperName,Implementation_Type__c,Implementing_Class__c,Implementing_Flow__c, Output_Creation_Class__c
                    from Service_Implementation__mdt
                    where DeveloperName = :serviceImplementationName];
            
            if (listServiceImplementationMDT.size() > 0) {
                ServiceImplementation.ServiceImplementationWrap siw = cacheMetadata(listServiceImplementationMDT[0].DeveloperName, listServiceImplementationMDT[0]);
                siw.serviceImplementationMetadataId = listServiceImplementationMDT[0].Id;
                return siw;
            }
            else {
                String exceptionString = ServiceErrorStrings.ERRORMSG_NO_SERVICE_IMPLEMENTATION_FOUND + serviceImplementationName;
                throw new Service.ServiceFrameworkException(exceptionString);
            }

        }
    }

    public static ServiceImplementation.ServiceImplementationWrap cacheMetadata(String serviceImplementationName, Service_Implementation__mdt newServiceImplementationMDT) {
        ServiceImplementation.ServiceImplementationWrap simpw = new ServiceImplementation.ServiceImplementationWrap();
        simpw.serviceImplementationName = serviceImplementationName;
        simpw.serviceImplementationMDT = newServiceImplementationMDT;
        mapServiceImplementationWrap.put(newServiceImplementationMDT.DeveloperName,simpw);
        return simpw;
    }

    public static ServiceImplementation.ServiceImplementationWrap updateCacheMetadata(Service_Implementation__mdt newServiceImplementationMDT) {
        ServiceImplementation.ServiceImplementationWrap simpw = ServiceImplementation.mapServiceImplementationWrap.get(newServiceImplementationMDT.DeveloperName);
        simpw.serviceImplementationMDT = newServiceImplementationMDT;
        return simpw;
    }


    // For test classes only, creates dummy custom metadata
    // instantiate a mininmal CMT record  
    // Add additional attributes to the variable returned and add to the CMT map.

    public static Service_Implementation__mdt createTestMetadata(String serviceImplementationName) {
        Service_Implementation__mdt serviceImplementationMDT = new Service_Implementation__mdt();
        serviceImplementationMDT.DeveloperName = serviceImplementationName;
        return serviceImplementationMDT;
    }



}