dxscale/core/serviceBase/objects/Service_Invocation_Override__c/Service_Invocation_Override__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Temporary overrides of service invocations, useful for stubbing, testing alternatives for selected users and unit tests</description>
    <label>Service Invocation Override</label>
</CustomObject>

dxscale/core/serviceBase/objects/Service_Invocation_Override__c/fields/Input_Creation_Class__c.field-meta.xml
<CustomField>
    <fullName>Input_Creation_Class__c</fullName>
    <description>Class name that implements the Input Interface Version that is used to create the input used in the service invocation. The Service and Service Version should not need to know this class name.</description>
    <inlineHelpText>Class name that implements the Input Interface Version that is used to create the input used in the service invocation. The Service and Service Version should not need to know this class name.</inlineHelpText>
    <label>Input Creation Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Invocation_Override__c/fields/Invocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Type__c</fullName>
    <description>Mimics the values of the fields with the same name in the custom metadata type Service Invocation. Custom Settings do not support picklists so this is a text value so this is textual. We allow an extra value in this field, namely "Stub"</description>
    <inlineHelpText>Mimics the values of the fields with the same name in the custom metadata type Service Invocation. Custom Settings do not support picklists so this is a text value so this is textual. We allow an extra value in this field, namely "Stub"</inlineHelpText>
    <label>Invocation Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Invocation_Override__c/fields/Metadata_Invoker_Id__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Invoker_Id__c</fullName>
    <description>A text field whose value should match the DeveloperName of the CMT Record that we are attempting to override</description>
    <inlineHelpText>A text field whose value should match the DeveloperName of the CMT Record that we are attempting to override</inlineHelpText>
    <label>Metadata Invoker Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Invocation_Override__c/fields/Override_Default__c.field-meta.xml
<CustomField>
    <fullName>Override_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked this override will be run unless another row with a specified User Permission is selected ahead of it because the  running user has the Custom Permission specified in that row. If checking this box ensure that the User Permission field is empty and note the Custom Metadata Type for this invocation will not be used in any circumstances</description>
    <inlineHelpText>If checked this override will be run unless another row with a specified User Permission is selected ahead of it because the  running user has the Custom Permission specified in that row. If checking this box ensure that the User Permission field is empty</inlineHelpText>
    <label>Override Default</label>
    <type>Checkbox</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Invocation_Override__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <description>Name of the Service, an implementation of which we are looking to invoke. Note that we use the Service name rather than a lookup as the Service may not be configured in all environments, in which case a stub method should be used.</description>
    <inlineHelpText>Name of the Service, an implementation of which we are looking to invoke. Note that we use the Service name rather than a lookup as the Service may not be configured in all environments, in which case a stub method should be used.</inlineHelpText>
    <label>Service Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

dxscale/core/serviceBase/objects/Service_Invocation_Override__c/fields/Stub_Class__c.field-meta.xml
<CustomField>
    <fullName>Stub_Class__c</fullName>
    <description>In development phases we may want to call a stub class for a service invocation. In this case we configure the Service Type to be stub and we create a Callable class to implement that stub and put its name as the Stub class.</description>
    <inlineHelpText>In development phases we may want to call a stub class for a service invocation. In this case we configure the Service Type to be stub and we create a Callable class to implement that stub and put its name as the Stub class.</inlineHelpText>
    <label>Stub Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/BillingService/methods/query/implementations/v1/classes/BillingServiceQueryAccountV1_Test.cls
@isTest
public class BillingServiceQueryAccountV1_Test {

    @TestSetup
    static void makeData(){

        //SET UP a stub for the Zuora Data call.
        Service_Invocation_Override__c sio3 = new Service_Invocation_Override__c();
        sio3.Name = 'ZuoraBillingAccount_Invocation_1';
        sio3.Metadata_Invoker_Id__c = 'ZuoraBillingAccount_Invocation_1';        
        sio3.Stub_Class__c = 'ZuoraBillingQueryV1_Stub';
        sio3.Invocation_Type__c = 'Stub';
        sio3.Override_Default__c = true;
        sio3.Input_Creation_Class__c = 'DynamicQueryConfigData';
        sio3.Service_Name__c = 'DynamicQueryService';
        insert sio3;              
                
        Account account = new Account(Name='testAccount');
        insert account;      
        
    }

    @isTest
    static void testGetBillingAccountInfo(){
        Account account = [select id from account where name = 'testAccount' limit 1];
        String correlationId = 'test12345';
        billing_IRequest request = new billing_Request(account.Id);
        GenericServiceInvoker invoker = new GenericServiceInvoker('BillingServiceV1_query');
        IService_Output_Master output = invoker.call(request);
        billing_QueryResponse reponse = (billing_QueryResponse)output;
        List<billing_BillingAccount> billingAccounts = reponse.getAccounts();
        System.assertEquals(1,billingAccounts.size(),'expected 1 records');
    }    


}