dxscale/sales/main/objects/Account/fields/Sage_Region__c.field-meta.xml
<CustomField>
    <fullName>Sage_Region__c</fullName>
    <label>Sage Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Region</valueSetName>
    </valueSet>
</CustomField>

dxscale/core/Intacct/objects/CountryMapping__mdt/CountryMapping__mdt.object-meta.xml
<CustomObject>
    <label>Country Mapping</label>
    <pluralLabel>CountryMappings</pluralLabel>
</CustomObject>

dxscale/core/Intacct/objects/CountryMapping__mdt/fields/Sage_Region__c.field-meta.xml
<CustomField>
    <fullName>Sage_Region__c</fullName>
    <description>Populate Region Based On Country</description>
    <label>Sage Region</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Annual_recurring_ACV_rollup__c.field-meta.xml
<CustomField>
    <fullName>Annual_recurring_ACV_rollup__c</fullName>
    <description>Annual recurring revenue for non-CBC products</description>
    <formula>IF( Contract_Term_Months__c &gt; 11, Monthly_Recurring_Revenue_rollup__c * 12, Monthly_Recurring_Revenue_rollup__c * Contract_Term_Months__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Annual recurring revenue for non-CBC products</inlineHelpText>
    <label>Annual Contract Value (ACV) - Formula</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Annual_Sales_Booking_ASB__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Booking_ASB__c</fullName>
    <inlineHelpText>Annual Sales Booking represents the annual recurring (renewable) part of a deal including the non-recurring (non-renewable)</inlineHelpText>
    <label>Annual Sales Booking (ASB)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Annual_Sales_Booking_Formula__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Booking_Formula__c</fullName>
    <formula>Annual_recurring_ACV_rollup__c + Non_recurring_Revenue_rollup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annual Sales Booking (ASB) - Formula</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Contact Email</description>
    <inlineHelpText>Primary Contact Email</inlineHelpText>
    <label>Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <defaultValue>&quot;Other&quot;</defaultValue>
    <description>For Reporting</description>
    <inlineHelpText>For Reporting</inlineHelpText>
    <label>Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Total_Contract_Value_TCV_forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Contract_Value_TCV_forecast__c</fullName>
    <inlineHelpText>Total Contract Value represents both recurring (renewable) and non-recurring (non-renewable) part of a deal over the full term of the contract</inlineHelpText>
    <label>Total Contract Value (TCV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityTrigger/classes/MapAccountCountryToOppCountry.cls
/*
 * Map the Account Billing Country or shipping Country to Opportunity.Country
 * Created by: Adam Annony
 */
public inherited sharing class MapAccountCountryToOppCountry {
    public void mapAccCtryToOppCtry(List<Opportunity> opps){
        Set<Id> accIds = new Set<Id>();
        Set<Id> ownIds = new Set<Id>();
        Map<Id, Account> accountMap ;
        Map<Id, User> ownerMap;
        for(Opportunity op :opps){
            accIds.add(op.AccountId);
            ownIds.add(op.OwnerId);
        }
        if(accIds.size() > 0){
            accountMap = new Map<Id, Account>([SELECT Id, Name, BillingCountry, ShippingCountry FROM Account WHERE Id IN :accIds WITH SECURITY_ENFORCED]);  
        }
        if(ownIds.size() > 0){
            ownerMap = new Map<Id, User>([SELECT Id, Country FROM User WHERE Id IN :ownIds WITH SECURITY_ENFORCED]);
        }
        for(Opportunity o :opps){
            String accBillingCtry = o.AccountId!=null&&accountMap.get(o.AccountId)!=null?accountMap.get(o.AccountId).BillingCountry:null;
            String accShippingCtry = o.AccountId!=null&&accountMap.get(o.AccountId)!=null?accountMap.get(o.AccountId).ShippingCountry:null;     
            if(accBillingCtry != null && o.Country__c != accBillingCtry){
                o.Country__c  = accBillingCtry;
            } else if(accBillingCtry == null && accShippingCtry != null){
                o.Country__c  = accShippingCtry;
            }
            else if(accBillingCtry != null && accShippingCtry != null && o.Country__c != accBillingCtry && o.Country__c != accShippingCtry){
                String ownerCountry = o.OwnerId!=null&&ownerMap.get(o.OwnerId)!=null?ownerMap.get(o.OwnerId).Country:null;
                o.Country__c = ownerCountry;
            }
        }
    }
    
   public void updateRegionOnOpportunity(Map<ID,Opportunity> oldOppMap,List<Opportunity> newOppList)
    {
        Map<String,String> crMap = new Map<String,String>();
        List<CountryMapping__mdt> clList = [select Sage_Region__c ,CountryName__c from CountryMapping__mdt WHERE CountryName__c!=null AND Sage_Region__c!=null WITH SECURITY_ENFORCED];
        for (CountryMapping__mdt cl : clList) {
            crMap.put(cl.CountryName__c,cl.Sage_Region__c);
        }
        for(Opportunity opp: newOppList) {
            if((opp.Country__c!=null)||(oldOppMap!=null && oldOppMap.get(opp.id)!=null && oldOppMap.get(opp.id).Country__c!=opp.Country__c)) {
                opp.Sage_Region__c=(crMap.get(opp.Country__c)!=null)?crMap.get(opp.Country__c):'Other'; 
                opp.Region__c=(crMap.get(opp.Country__c)!=null)?crMap.get(opp.Country__c):'Other'; 
            }
        }
    }
    
   //EAD-266 
   public void oppsWithQuotes(Map<ID,Opportunity> oldOppMap,List<Opportunity> newOppList, Map<ID,Opportunity> newOppMap) {
        Set<String> oppIds = new Set<String>();
        for(Opportunity opp : newOppList) {
            if(oldOppMap != null && oldOppMap.get(opp.Id)!=null && oldOppMap.get(opp.Id).AccountId != opp.AccountId){
                //collect all the opportunity Ids where the Account is changed
                oppIds.add(opp.Id);
            }
        }
        //Retrieve Quotes for each Opp which are sent ot Z-billing
        // Running outside testing context this required to be fixed using service framework or seperate package
        if (!Test.isRunningTest()) {
            List<SObject> lQuote = (List<SObject>) Database.query( ' SELECT Id, zqu__Opportunity__c FROM zqu__Quote__c '
                                                   + ' WHERE zqu__Status__c = \'Sent to Z-Billing\' '
                                                        + ' AND zqu__Opportunity__c IN :oppIds WITH SECURITY_ENFORCED');
            for (SObject eachQuote :lQuote) {
                newOppMap.get((Id) eachQuote.get('zqu__Opportunity__c')).addError(Label.AccountChangeError);
            }
        }
    }
    
    //EAD - 430 update to ACV/TCV process on Opportunity.
    public void updateTCV(List<Opportunity> newOppList)
    {
        for(Opportunity opp : newOppList)
        {
            if(opp.Amount == null){
            	opp.Amount = 0;    
            }
            if(opp.Total_Contract_Value_TCV_forecast__c == null){
                opp.Total_Contract_Value_TCV_forecast__c = 0;  
            }
            if(opp.Annual_recurring_ACV_rollup__c > 0){
            	opp.Amount_ACV__c = opp.Annual_recurring_ACV_rollup__c;
            }
            if(opp.Total_Contract_Value_TCV__c > 0){
                opp.Total_Contract_Value_TCV_forecast__c = opp.Total_Contract_Value_TCV__c;  
            }
            if(opp.Annual_Sales_Booking_Formula__c > 0){
                opp.Annual_Sales_Booking_ASB__c = opp.Annual_Sales_Booking_Formula__c;  
            }
        }
    }  
      
	/** public void copyContactDetails(List<Opportunity> newOppList){
        Set<Id> accIds = new Set<Id>();
        Map<String, Contact> accIdContMap = new Map<String, Contact>();
        Map<String, Contact> hasOptedOutContactsMap = new Map<String, Contact>();
        for(Opportunity opp :newOppList){
            accIds.add(opp.AccountId);
        }
        List<Contact> contacts = [SELECT Id, Name, HasOptedOutOfEmail, AccountId, Email FROM Contact 
                                 WHERE AccountId IN :accIds 
                                  //AND HasOptedOutOfEmail = false 
                                 ORDER BY CreatedDate ASC];
        for(Contact c :contacts){
            if(c.HasOptedOutOfEmail == false){
                accIdContMap.put(c.AccountId, c);
            } else{
                hasOptedOutContactsMap.put(c.AccountId, c);
            }
            
        }
        for(Opportunity opp :newOppList){
            if(accIdContMap.get(opp.AccountId)!=null){
                opp.Email__c = accIdContMap.get(opp.AccountId).Email;
            } else if(hasOptedOutContactsMap.get(opp.AccountId)!=null){
                opp.Email__c = hasOptedOutContactsMap.get(opp.AccountId).Email;
            }
        }
    } **/
}