dxscale/core/exceptionLogging/objects/ExceptionEvent__e/ExceptionEvent__e.object-meta.xml
<CustomObject>
    <label>Exception Event</label>
    <pluralLabel>Exception Events</pluralLabel>
</CustomObject>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>ClassName</description>
    <label>ClassName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/ExceptionCause__c.field-meta.xml
<CustomField>
    <fullName>ExceptionCause__c</fullName>
    <label>Exception Cause</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Where relevant the record Id that was processing and errored</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/exceptionLogging/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to hold log messages from the SendtoZBilling and ZuoraInvoiceUpdateBatch custom apex code.  Designed to be generic so can be used to hold any log message in the future.</description>
    <label>Logger</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dxscale/core/exceptionLogging/objects/Logger__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <description>CorrelationId for tracking issues that may have been external requests</description>
    <label>Correlation Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/objects/Logger__c/fields/Exception_DML_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_DML_Message__c</fullName>
    <label>Exception DML Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/exceptionLogging/objects/Logger__c/fields/Exception_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Error_Message__c</fullName>
    <label>Exception Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/exceptionLogging/objects/Logger__c/fields/Exception_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>Exception_StackTrace__c</fullName>
    <label>Exception StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/exceptionLogging/objects/Logger__c/fields/Record_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Name_Id__c</fullName>
    <description>This would store record Id or Name of the record on which error occurred while processing</description>
    <label>Record Name/Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/classes/ExceptionEvent_Helper.cls
public inherited sharing class ExceptionEvent_Helper {
   
    public static void processEventToLogger(List<ExceptionEvent__e> exceptionEvents) {
        //list of hold the log records that needs to be inserted from the platform events
        List<Logger__c> logsToInsert = new List<Logger__c>();

        //looping through each platform event that gets published and inserting log records
        for (ExceptionEvent__e eve : exceptionEvents){
            Logger__c log = new Logger__c();
            log.Exception_StackTrace__c = eve.StackTrace__c;
            log.Record_Name_Id__c = eve.Record_Id__c;
            log.Name = eve.ClassName__c;
            log.Exception_Error_Message__c = eve.ErrorMessage__c;
            log.Exception_Type__c = eve.ExceptionType__c;
            log.Exception_DML_Message__c = eve.ExceptionCause__c;
            if(!Test.isRunningTest()){
                log.OwnerId = eve.CreatedById;
            }
            log.Correlation_Id__c = eve.Correlation_Id__c;
            logsToInsert.add(log);
        }
        insert logsToInsert;
        
    }

}