dxscale/core/exceptionLogging/objects/ExceptionEvent__e/ExceptionEvent__e.object-meta.xml
<CustomObject>
    <label>Exception Event</label>
    <pluralLabel>Exception Events</pluralLabel>
</CustomObject>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>ClassName</description>
    <label>ClassName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/exceptionLogging/objects/ExceptionEvent__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Where relevant the record Id that was processing and errored</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to hold log messages from the SendtoZBilling and ZuoraInvoiceUpdateBatch custom apex code.  Designed to be generic so can be used to hold any log message in the future.</description>
    <label>Logger</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dxscale/core/exceptionLogging/objects/Logger__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <description>CorrelationId for tracking issues that may have been external requests</description>
    <label>Correlation Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/objects/Logger__c/fields/Record_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Name_Id__c</fullName>
    <description>This would store record Id or Name of the record on which error occurred while processing</description>
    <label>Record Name/Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/exceptionLogging/classes/ExceptionEvent_TriggerHandler_Test.cls
@isTest
public class ExceptionEvent_TriggerHandler_Test {

    
    @isTest
    static void testPublish(){

        ExceptionEvent__e event = new ExceptionEvent__e();
        event.ClassName__c = 'MyTestClassX1';
        event.Correlation_Id__c = 'test-123-456-789';
        event.Record_Id__c = 'recordId';
        event.ErrorMessage__c = 'Test Error Message';
        
        ExceptionEvent_TriggerHandler handler = new ExceptionEvent_TriggerHandler();
        handler.setTriggerData(new List<SObject>{event},null,null);

        Test.startTest();
            try{
                handler.call('onAfterInsert', null);
            }catch(Exception e){
                // as this is testing the handler (not he bus) all we can assert is it didn't fail
                System.assertEquals(true, false,'Should not have thrown an error, force failure : ' + e.getStackTraceString());
            }
            
        Test.stopTest();
        List<Logger__c> logs = [Select Id,Name,Record_Name_Id__c From Logger__c];
        System.assertEquals(1, logs.size(),'expected 1 log entry');
        System.assertEquals('MyTestClassX1', logs[0].Name,'expected The class to be passed on');
    }
}