dxscale/sales/main/objects/Opportunity/fields/Annual_Sales_Booking_ASB__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Booking_ASB__c</fullName>
    <inlineHelpText>Annual Sales Booking represents the annual recurring (renewable) part of a deal including the non-recurring (non-renewable)</inlineHelpText>
    <label>Annual Sales Booking (ASB)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Total_Contract_Value_TCV_forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Contract_Value_TCV_forecast__c</fullName>
    <inlineHelpText>Total Contract Value represents both recurring (renewable) and non-recurring (non-renewable) part of a deal over the full term of the contract</inlineHelpText>
    <label>Total Contract Value (TCV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/Opportunity_Assignment__c.object-meta.xml
<CustomObject>
    <description>Used to trigger update to Opportunity record owners via the Data Import Wizard</description>
    <label>Opportunity Assignment</label>
    <nameField>
        <displayFormat>OASS-{000000}</displayFormat>
        <label>Opportunity Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Amount_ACV__c.field-meta.xml
<CustomField>
    <fullName>Amount_ACV__c</fullName>
    <description>Same as Opportunity-Amount_ACV</description>
    <label>Annual Contract Value (ACV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Annual_Sales_Booking_ASB__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Booking_ASB__c</fullName>
    <description>Same as Opportunity-Annual_Sales_Booking_ASB__c</description>
    <label>Annual Sales Booking (ASB)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User whom the target Opportunity is intended to be owned by.</description>
    <inlineHelpText>User whom the target Opportunity is intended to be owned by.</inlineHelpText>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <description>Same as Opportunity-Channel_Type</description>
    <label>Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <description>Same as Opportunity-CloseDate</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Contract_Due_Date_For_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date_For_Renewal__c</fullName>
    <description>Same as Opportunity-Contract_Due_Date_For_Renewal</description>
    <label>Due Date For Renewal</label>
    <type>Date</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Discovery_Notes__c.field-meta.xml
<CustomField>
    <fullName>Discovery_Notes__c</fullName>
    <description>Same as Opportunity-Qualification Notes</description>
    <label>Qualification Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity which requires owner to be reassigned.</description>
    <inlineHelpText>Opportunity which requires owner to be reassigned.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Assignments</relationshipLabel>
    <relationshipName>Opportunity_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Same as Opportunity-Opportunity Name</description>
    <label>Opportunity Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Diagnostic information for failed updates</description>
    <inlineHelpText>Diagnostic information for failed updates</inlineHelpText>
    <label>Outcome</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Pain_Points_w_Current_Solution__c.field-meta.xml
<CustomField>
    <fullName>Pain_Points_w_Current_Solution__c</fullName>
    <description>Same as Opportunity-Pain_Points_w_Current_Solution__c</description>
    <label>Other Pain Points w/ Current Solution</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether assignment of new Opportunity owner was successful.</description>
    <inlineHelpText>Indicates whether assignment of new Opportunity owner was successful.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Total_Contract_Value_TCV_forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Contract_Value_TCV_forecast__c</fullName>
    <description>Same as Opportunity-Total_Contract_Value_TCV_forecast</description>
    <label>Total Contract Value (TCV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Why_We_Lost__c.field-meta.xml
<CustomField>
    <fullName>Why_We_Lost__c</fullName>
    <description>Same as Opportunity-Why_We_Lost__c</description>
    <label>Win / Loss / Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>FaaS</fullName>
            </value>
            <value>
                <fullName>No Decision</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product Integration</fullName>
            </value>
            <value>
                <fullName>Proposition</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>System Intergration</fullName>
            </value>
            <value>
                <fullName>User Experience</fullName>
            </value>
            <value>
                <fullName>Nurture Lead</fullName>
            </value>
            <value>
                <fullName>Rejected SQL</fullName>
            </value>
            <value>
                <fullName>Payment Method (e.g. Monthly, annually)</fullName>
            </value>
            <value>
                <fullName>Product Functionality / Usability</fullName>
            </value>
            <value>
                <fullName>Sales/Marketing Process</fullName>
            </value>
            <value>
                <fullName>Relationship with Sage</fullName>
            </value>
            <value>
                <fullName>Change in customer&apos;s business</fullName>
            </value>
            <value>
                <fullName>Unable to contact</fullName>
            </value>
            <value>
                <fullName>No reason specified</fullName>
            </value>
            <value>
                <fullName>Payment Method</fullName>
            </value>
            <value>
                <fullName>Production Functionality / Usability</fullName>
            </value>
            <value>
                <fullName>References</fullName>
            </value>
            <value>
                <fullName>Timescale to implement</fullName>
            </value>
            <value>
                <fullName>Compliance with legislation</fullName>
            </value>
            <value>
                <fullName>Not ready to make a decision</fullName>
            </value>
            <value>
                <fullName>False Opportunity</fullName>
            </value>
            <value>
                <fullName>Withdrawal from bid process</fullName>
            </value>
            <value>
                <fullName>No Project</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Needs Default</fullName>
            </value>
            <value>
                <fullName>No Decision Maker</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Win_Loss_Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>Win_Loss_Other_Reason__c</fullName>
    <description>Same as Opportunity-Win_Loss_Other_Reason</description>
    <label>Win / Loss / Reject Comments</label>
    <type>TextArea</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Win_Loss_Reject_Reasons_Level1__c.field-meta.xml
<CustomField>
    <fullName>Win_Loss_Reject_Reasons_Level1__c</fullName>
    <description>Same as Opportunity-Win_Loss_Reject_Reasons_Level1__c</description>
    <label>Win/Loss/Reject Reasons Level1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Won From NA</fullName>
            </value>
            <value>
                <fullName>Won From UK</fullName>
            </value>
            <value>
                <fullName>Lost From NA</fullName>
            </value>
            <value>
                <fullName>Lost From UK</fullName>
            </value>
            <value>
                <fullName>Feature Requirement</fullName>
            </value>
            <value>
                <fullName>Retention Conversation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>OutSourced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Win_Loss_Reject_Reasons_Level2__c.field-meta.xml
<CustomField>
    <fullName>Win_Loss_Reject_Reasons_Level2__c</fullName>
    <description>Same as Opportunity-Win_Loss_Reject_Reasons_Level2</description>
    <label>Win/Loss/Reject Reasons Level2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Xero</fullName>
            </value>
            <value>
                <fullName>Quickbooks</fullName>
            </value>
            <value>
                <fullName>Moneysoft</fullName>
            </value>
            <value>
                <fullName>Iris</fullName>
            </value>
            <value>
                <fullName>Brightpearl</fullName>
            </value>
            <value>
                <fullName>Deskera</fullName>
            </value>
            <value>
                <fullName>Dolibarr</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics GP</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics NAV</fullName>
            </value>
            <value>
                <fullName>Odoo</fullName>
            </value>
            <value>
                <fullName>Stafiz</fullName>
            </value>
            <value>
                <fullName>SYSPRO</fullName>
            </value>
            <value>
                <fullName>Upgrade Product</fullName>
            </value>
            <value>
                <fullName>Upgrade Support</fullName>
            </value>
            <value>
                <fullName>Downgrade Product</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Full Value</fullName>
            </value>
            <value>
                <fullName>Downgrade Support</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>BP</fullName>
            </value>
            <value>
                <fullName>No migration Tool</fullName>
            </value>
            <value>
                <fullName>Bureau</fullName>
            </value>
            <value>
                <fullName>Other (please specify in notes)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/classes/OpportunityAssignmentHelper.cls
/*
 * OpportunityAssignmentHelper
 * ----------------------------
 * Invoked by the OpportunityAssignmentTrigger and OpportunityAssignmentHandler class when an Opportunity Assignment record is inserted
 * Updates the specified Opportunity's owner with the user identified in the Assignee__c field
 * via a batched job - a simple update was resulting in Apex CPU limits exceeded on >50 Opportunity updates
 */
public inherited sharing class OpportunityAssignmentHelper {
    static String CLASSNAME = 'OpportunityAssignmentHelper';
  
     /**
     * @description CCORE-2152 Mass reassign Opportunities via the Data Import Wizard
     * @param newOAs list of new trigger records
     */
    public static void presetStatusOpportunityAssignments(List<Opportunity_Assignment__c> newOAs) {
      try{  
         LogControl.push('presetStatusOpportunityAssignments', CLASSNAME);
         List<Opportunity_Assignment__c> lstOAs = new List<Opportunity_Assignment__c>();
         // Unique set of Opportunities to prevent duplicate updates to same Opportunity
         Set<Id> uniqueOpportunities = new Set<Id>();        
         for (Opportunity_Assignment__c oa : newOAs) {    
            Opportunity opp = new Opportunity();
            opp.Id = oa.Opportunity__c;           
            if (uniqueOpportunities.contains(oa.Opportunity__c)) {
                // duplicate Opportunity spotted
                oa.Status__c = 'Duplicate';
                oa.Outcome__c = '';
            } else {
                oa.Status__c = 'Request';
                oa.Outcome__c = '';
                uniqueOpportunities.add(opp.Id);
            }    
         }    
         } catch (Exception e) { 
           LogControl.debugException(e); 
         } finally { 
           LogControl.pop(); 
       }
    }    

    /**
     * @description CCORE-2152 Mass reassign Opportunities via the Data Import Wizard
     * @param newOAs list of new trigger records
     */
    public static void assignOpportunities(List<Opportunity_Assignment__c> newOAs) {
        LogControl.push('assignOpportunities', CLASSNAME);
        List<Opportunity_Assignment__c> assignmentsForUpdate = new List<Opportunity_Assignment__c>();
        // Map to allow recording of updates in the original Opportunity Assignment records and the Opportunities themselves
        Map<Opportunity_Assignment__c, Opportunity> mapAssignmentsToOpportunities = new Map<Opportunity_Assignment__c, Opportunity>();
        // Unique set of Opportunities to prevent duplicate updates to same Opportunity
        Set<Id> uniqueOpportunities = new Set<Id>();
        // "Create" Opportunities for update
        for (Opportunity_Assignment__c oa : newOAs) {
            if (uniqueOpportunities.contains(oa.Opportunity__c)) {
                // duplicate Opportunity spotted
                Opportunity_Assignment__c assignmentForUpdate = new Opportunity_Assignment__c();
                assignmentForUpdate.Id = oa.Id;
                assignmentForUpdate.Status__c = 'Duplicate';
                assignmentForUpdate.Outcome__c = '';
                assignmentsForUpdate.add(assignmentForUpdate);
            } else {
                Opportunity opp = new Opportunity();
                opp.Id = oa.Opportunity__c;
                
                if (!String.isBlank(oa.Assignee__c)){
                   opp.OwnerId = oa.Assignee__c;
                }    
                // 2020/06/11 bphan EAD 1539
                if (!String.isBlank(oa.Assignee__c)){
                   opp.Amount_ACV__c = oa.Amount_ACV__c;
                }
                if ((oa.Annual_Sales_Booking_ASB__c <> NULL) && (oa.Annual_Sales_Booking_ASB__c <> 0)) {
                   opp.Annual_Sales_Booking_ASB__c = oa.Annual_Sales_Booking_ASB__c;
                }
                if (!String.isBlank(oa.Channel_Type__c)){
                   opp.Channel_Type__c = oa.Channel_Type__c;
                }
                if (!String.isBlank(oa.CurrencyIsoCode)){
                   opp.CurrencyIsoCode = oa.CurrencyIsoCode;
                }
                if (!String.isBlank(oa.Opportunity_Name__c)){
                     opp.Name = oa.Opportunity_Name__c;
                }
                if (!String.isBlank(oa.Pain_Points_w_Current_Solution__c)){
                  opp.Pain_Points_w_Current_Solution__c = oa.Pain_Points_w_Current_Solution__c;
                }
                if (!String.isBlank(oa.Discovery_Notes__c)){
                     opp.Discovery_Notes__c = oa.Discovery_Notes__c;                
                }
                if ((oa.Total_Contract_Value_TCV_forecast__c <> NULL) && (oa.Total_Contract_Value_TCV_forecast__c <> 0)) {
                     opp.Total_Contract_Value_TCV_forecast__c = oa.Total_Contract_Value_TCV_forecast__c;
                }
                if (!String.isBlank(oa.Win_Loss_Other_Reason__c)){
                     opp.Win_Loss_Other_Reason__c = oa.Win_Loss_Other_Reason__c;
                }
                if (oa.CloseDate__c <> NULL){
                     opp.CloseDate = oa.CloseDate__c;
                }
                if (oa.Contract_Due_Date_For_Renewal__c <> NULL){
                     opp.Contract_Due_Date_For_Renewal__c = oa.Contract_Due_Date_For_Renewal__c;  
                }
                if (!String.isBlank(oa.Why_We_Lost__c)){
                     opp.Why_We_Lost__c = oa.Why_We_Lost__c;
                }                
                if (!String.isBlank(oa.Win_Loss_Reject_Reasons_Level1__c)){
                     opp.Win_Loss_Reject_Reasons_Level1__c = oa.Win_Loss_Reject_Reasons_Level1__c;
                }
                if (!String.isBlank(oa.Win_Loss_Reject_Reasons_Level2__c)){
                     opp.Win_Loss_Reject_Reasons_Level2__c = oa.Win_Loss_Reject_Reasons_Level2__c;
                }
                if (!String.isBlank(oa.Win_Loss_Reject_Reasons_Level3__c)){
                   opp.Win_Loss_Reject_Reasons_Level3__c = oa.Win_Loss_Reject_Reasons_Level3__c;
                }
                if (!String.isBlank(oa.Stage__c)){
                   opp.StageName = oa.Stage__c;
                }
                if (!String.isBlank(oa.Lead_Source__c)){
                   opp.Lead_Source__c = oa.Lead_Source__c;             
                }
                
                // Adding all new renewal fields as per the request on EAD-1991
                // Date 10-11-2020
                if (!String.isBlank(oa.Renewal_BillingPeriod__c)){
                   opp.Renewal_BillingPeriod__c = oa.Renewal_BillingPeriod__c;             
                }
                if (!String.isBlank(oa.Renewal_Yearlyvaluebeingrenewed__c)){
                   opp.Renewal_Yearlyvaluebeingrenewed__c = oa.Renewal_Yearlyvaluebeingrenewed__c;             
                }
                if (!String.isBlank(oa.Renewal_Status__c)){
                   opp.Renewal_Status__c = oa.Renewal_Status__c;             
                }
                if (oa.Renewal_PromisePaiddate__c <> NULL){
                     opp.Renewal_PromisePaiddate__c = oa.Renewal_PromisePaiddate__c;
                }
                if (oa.Renewal_InterventionDate__c <> NULL){
                     opp.Renewal_InterventionDate__c = oa.Renewal_InterventionDate__c;
                }
                if (oa.Renewal_FirstBillingDate__c <> NULL){
                     opp.Renewal_FirstBillingDate__c = oa.Renewal_FirstBillingDate__c;
                }
                if (oa.Renewal_Billingfilefullvalue__c <> NULL){
                     opp.Renewal_Billingfilefullvalue__c = oa.Renewal_Billingfilefullvalue__c;
                }
               
                

                Opportunity_Assignment__c oaReq = new Opportunity_Assignment__c();
                oaReq.Id = oa.Id;
                oaReq.Status__c = 'Request';
                oaReq.Outcome__c = '';
                assignmentsForUpdate.add(oaReq);
                
                                            
                mapAssignmentsToOpportunities.put(oa, opp);
                uniqueOpportunities.add(opp.Id);
            }
        }
        // Kick off the batch to update Opportunities (and Opportunity Assignment status)
        // Update the Opportunity Assignments which attempted to update Opportunities already being reassigned
        Database.update(assignmentsForUpdate, false);
        if (!system.isBatch() && mapAssignmentsToOpportunities.size() > 0){
             Database.executeBatch(new OpportunityAssignmentBatch(mapAssignmentsToOpportunities), 200);
        }    

    }
}