dxscale/sales/main/objects/Opportunity/fields/Annual_Sales_Booking_ASB__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Booking_ASB__c</fullName>
    <inlineHelpText>Annual Sales Booking represents the annual recurring (renewable) part of a deal including the non-recurring (non-renewable)</inlineHelpText>
    <label>Annual Sales Booking (ASB)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/main/objects/Opportunity/fields/Total_Contract_Value_TCV_forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Contract_Value_TCV_forecast__c</fullName>
    <inlineHelpText>Total Contract Value represents both recurring (renewable) and non-recurring (non-renewable) part of a deal over the full term of the contract</inlineHelpText>
    <label>Total Contract Value (TCV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/Opportunity_Assignment__c.object-meta.xml
<CustomObject>
    <description>Used to trigger update to Opportunity record owners via the Data Import Wizard</description>
    <label>Opportunity Assignment</label>
    <nameField>
        <displayFormat>OASS-{000000}</displayFormat>
        <label>Opportunity Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Amount_ACV__c.field-meta.xml
<CustomField>
    <fullName>Amount_ACV__c</fullName>
    <description>Same as Opportunity-Amount_ACV</description>
    <label>Annual Contract Value (ACV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Annual_Sales_Booking_ASB__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Booking_ASB__c</fullName>
    <description>Same as Opportunity-Annual_Sales_Booking_ASB__c</description>
    <label>Annual Sales Booking (ASB)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User whom the target Opportunity is intended to be owned by.</description>
    <inlineHelpText>User whom the target Opportunity is intended to be owned by.</inlineHelpText>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <description>Same as Opportunity-Channel_Type</description>
    <label>Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <description>Same as Opportunity-CloseDate</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Contract_Due_Date_For_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date_For_Renewal__c</fullName>
    <description>Same as Opportunity-Contract_Due_Date_For_Renewal</description>
    <label>Due Date For Renewal</label>
    <type>Date</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Discovery_Notes__c.field-meta.xml
<CustomField>
    <fullName>Discovery_Notes__c</fullName>
    <description>Same as Opportunity-Qualification Notes</description>
    <label>Qualification Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>Same as Opportunity-Opportunity/Lead Source</description>
    <label>Opportunity/Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity which requires owner to be reassigned.</description>
    <inlineHelpText>Opportunity which requires owner to be reassigned.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Assignments</relationshipLabel>
    <relationshipName>Opportunity_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Same as Opportunity-Opportunity Name</description>
    <label>Opportunity Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Pain_Points_w_Current_Solution__c.field-meta.xml
<CustomField>
    <fullName>Pain_Points_w_Current_Solution__c</fullName>
    <description>Same as Opportunity-Pain_Points_w_Current_Solution__c</description>
    <label>Other Pain Points w/ Current Solution</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Same as Opportunity-Stage</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Evaluating</fullName>
            </value>
            <value>
                <fullName>Solution Validation</fullName>
            </value>
            <value>
                <fullName>Confirming Value</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Qualify</fullName>
            </value>
            <value>
                <fullName>Selection</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
                <isActive>false</isActive>
                <label>Negotiating</label>
            </value>
            <value>
                <fullName>Qualification</fullName>
                <isActive>false</isActive>
                <label>Qualification</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Total_Contract_Value_TCV_forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Contract_Value_TCV_forecast__c</fullName>
    <description>Same as Opportunity-Total_Contract_Value_TCV_forecast</description>
    <label>Total Contract Value (TCV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Why_We_Lost__c.field-meta.xml
<CustomField>
    <fullName>Why_We_Lost__c</fullName>
    <description>Same as Opportunity-Why_We_Lost__c</description>
    <label>Win / Loss / Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>FaaS</fullName>
            </value>
            <value>
                <fullName>No Decision</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product Integration</fullName>
            </value>
            <value>
                <fullName>Proposition</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>System Intergration</fullName>
            </value>
            <value>
                <fullName>User Experience</fullName>
            </value>
            <value>
                <fullName>Nurture Lead</fullName>
            </value>
            <value>
                <fullName>Rejected SQL</fullName>
            </value>
            <value>
                <fullName>Payment Method (e.g. Monthly, annually)</fullName>
            </value>
            <value>
                <fullName>Product Functionality / Usability</fullName>
            </value>
            <value>
                <fullName>Sales/Marketing Process</fullName>
            </value>
            <value>
                <fullName>Relationship with Sage</fullName>
            </value>
            <value>
                <fullName>Change in customer&apos;s business</fullName>
            </value>
            <value>
                <fullName>Unable to contact</fullName>
            </value>
            <value>
                <fullName>No reason specified</fullName>
            </value>
            <value>
                <fullName>Payment Method</fullName>
            </value>
            <value>
                <fullName>Production Functionality / Usability</fullName>
            </value>
            <value>
                <fullName>References</fullName>
            </value>
            <value>
                <fullName>Timescale to implement</fullName>
            </value>
            <value>
                <fullName>Compliance with legislation</fullName>
            </value>
            <value>
                <fullName>Not ready to make a decision</fullName>
            </value>
            <value>
                <fullName>False Opportunity</fullName>
            </value>
            <value>
                <fullName>Withdrawal from bid process</fullName>
            </value>
            <value>
                <fullName>No Project</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Needs Default</fullName>
            </value>
            <value>
                <fullName>No Decision Maker</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Won from Competitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Win_Loss_Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>Win_Loss_Other_Reason__c</fullName>
    <description>Same as Opportunity-Win_Loss_Other_Reason</description>
    <label>Win / Loss / Reject Comments</label>
    <type>TextArea</type>
</CustomField>

dxscale/sales/opportunityAssignment/objects/Opportunity_Assignment__c/fields/Win_Loss_Reject_Reasons_Level1__c.field-meta.xml
<CustomField>
    <fullName>Win_Loss_Reject_Reasons_Level1__c</fullName>
    <description>Same as Opportunity-Win_Loss_Reject_Reasons_Level1__c</description>
    <label>Win/Loss/Reject Reasons Level1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Won From NA</fullName>
            </value>
            <value>
                <fullName>Won From UK</fullName>
            </value>
            <value>
                <fullName>Lost From NA</fullName>
            </value>
            <value>
                <fullName>Lost From UK</fullName>
            </value>
            <value>
                <fullName>Feature Requirement</fullName>
            </value>
            <value>
                <fullName>Retention Conversation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>OutSourced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/main/objects/OpportunityControlSwitch__c/OpportunityControlSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to control automations on the opportunity object</description>
    <label>Opportunity Control Switch</label>
</CustomObject>

dxscale/sales/main/objects/OpportunityControlSwitch__c/fields/RunValidationRules__c.field-meta.xml
<CustomField>
    <fullName>RunValidationRules__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to control the execution of workflows on the opportunity object</description>
    <inlineHelpText>Checkbox to control the execution of workflows on the opportunity object</inlineHelpText>
    <label>Run Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

dxscale/sales/opportunityAssignment/classes/OpportunityAssignmentTriggerTest.cls
/*
 * OpportunityAssignmentTriggerTest
 * Tests the OpportunityAssignmentTrigger and its helper class
 */
@IsTest
public class OpportunityAssignmentTriggerTest {
    @TestSetup
    static void dataSetup() {
      Profile p1 = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u1 = new User(Alias='usera',
                           Email='a@aaa.com',
                           EmailEncodingKey='ISO-8859-1',
                           FirstName='aaa',
                           LastName='aaa',
                           LanguageLocaleKey='en_US',
                           LocaleSidKey='en_GB',
                           ProfileId=p1.Id,
                           TimeZoneSidKey='Europe/London',
                           CommunityNickname = 'aaa',
                           IsActive=true,
                           Username='a@aaa.com.sage');
        insert u1;
        User u2 = new User(Alias='userb',
                           Email='b@bbb.com',
                           EmailEncodingKey='ISO-8859-1',
                           FirstName='bbb',
                           LastName='bbb',
                           LanguageLocaleKey='en_US',
                           LocaleSidKey='en_GB',
                           ProfileId=p1.Id,
                           TimeZoneSidKey='Europe/London',
                           CommunityNickname = 'bbb',
                           IsActive=true,
                           Username='b@bbb.com.sage');
        insert u2;
        Account acc = new Account(Name='testAccount',
                                  Type='Customer',
                                  BillingCountry='United Kingdom',
                                  BillingCity='Blyth',
                                  BillingStreet='Any Street');
        insert acc;
        RecordType rt = [SELECT Id FROM RecordType WHERE Name =:Label.OPP_RT_MED_STANDARD];
        // 10 Opportunities as 201 was breaking CPU limits
        // The 10th has no Lead_Source__c but can be inserted because the validation rule on this field is bypassed via missing custom setting
        List<Opportunity> oppList = new List<Opportunity>();
        for (Integer i=0; i<10; i++) {
            Opportunity opp = new Opportunity();
            opp.AccountId = acc.Id;
            opp.Name = 'TestOpp_' + i;
            opp.StageName = 'Qualification';
            opp.CloseDate = System.today() - 2;  // 06/12/2020 bphan EAD-1539
            opp.RecordTypeId = rt.Id;
            opp.OwnerId = u1.Id;
            if (i<9) { opp.Lead_Source__c = 'Marketing'; }
            oppList.add(opp);
        } 
        insert oppList;
    }
    
    @IsTest
    static void testOpportunityAssignment() {       
        System.debug('OpportunityAssignmentTriggerTest: testOpportunityAssignment START');
        // Retrieve test data
        List<Opportunity> oppIds = [SELECT Id FROM Opportunity];
        User assignee = [SELECT Id FROM User WHERE Alias='userb'][0];       
        // Switch on validation rules which have the bypass setting to catch Opportunity errors
        OpportunityControlSwitch__c setting = new OpportunityControlSwitch__c ();
		setting.Name = 'VR';
		setting.RunValidationRules__c = true;
		insert setting;
        
        Test.startTest();
        List<Opportunity_Assignment__c> oaList = new List<Opportunity_Assignment__c>();
        // 10 opportunity assignments (though one should fail validation on save due to empty Lead_Source__c field)
        for (Integer i=0; i<9; i++) {
            Opportunity_Assignment__c oa = new Opportunity_Assignment__c();
            oa.Opportunity__c = oppIds[i].Id;
            oa.Assignee__c = assignee.Id;
            //06/12/2020 bphan EAD_1539
            oa.CloseDate__c = System.today();
            oa.Amount_ACV__c = 100;
            oa.Annual_Sales_Booking_ASB__c = 100;
            oa.Channel_Type__c = 'Direct';
            //oa.CurrencyIsoCode = 'USD';
            oa.Opportunity_Name__c = 'OppAss ' + i;
            oa.Contract_Due_Date_For_Renewal__c = System.today() + 10;
            oa.Pain_Points_w_Current_Solution__c = 'OppAss painpoint solution' + i;
            oa.Discovery_Notes__c = 'OppAss notes ' + i;
            oa.Stage__c = Label.Opportunity_Sales_Stages_Closed_Won;
            oa.Total_Contract_Value_TCV_forecast__c = 200;
            oa.Win_Loss_Other_Reason__c = 'OppAss win loss reason ' + i;
            oa.Why_We_Lost__c = 'Won from Competitor';
            oa.Win_Loss_Reject_Reasons_Level1__c = '';
            oa.Win_Loss_Reject_Reasons_Level2__c = '';
            oa.Win_Loss_Reject_Reasons_Level3__c = '';   
            oa.Renewal_BillingPeriod__c  = 'Quarterly';
            oa.Renewal_Yearlyvaluebeingrenewed__c = '1 year';
            oa.Renewal_Status__c = 'Paid';
            oa.Renewal_PromisePaiddate__c = Date.today();
            oa.Renewal_InterventionDate__c = Date.today();
            oa.Renewal_FirstBillingDate__c = Date.today();
            oa.Renewal_Billingfilefullvalue__c =10;
             
            if (i<9) { oa.Lead_Source__c = 'Marketplace'; }

            oaList.add(oa);
        }
        // Add a duplicate Opportunity update
        Opportunity_Assignment__c oad = new Opportunity_Assignment__c(); 
        oad.Opportunity__c = oppIds[0].Id;
        oad.Assignee__c = assignee.Id;
        oaList.add(oad);
        
        // Inserting the Opportunity_Assignment__c objects should fire the associated trigger
        insert oaList;   
        // Ensure trigger completed (and hopefully the batch)
        Test.stopTest();
        
        // Check only the good Opportunities changed owner
        Integer goodOpps = [SELECT COUNT() 
                            FROM Opportunity
                            WHERE OwnerId = :assignee.Id];
        System.debug('OpportunityAssignmentTriggerTest: Good Opps');
        System.assertEquals(9, goodOpps);
        // Check all of the Opportunity Assignments changed status appropriately
        Integer retOAs = [SELECT COUNT()  
                          FROM Opportunity_Assignment__c
                          WHERE Status__c = 'Success'];
        System.debug('OpportunityAssignmentTriggerTest: Success');
        System.assertEquals(9, retOAs);
        Integer retOAs2 = [SELECT COUNT()  
                          FROM Opportunity_Assignment__c
                          WHERE Status__c = 'Fail'];
         System.debug('OpportunityAssignmentTriggerTest: Fail');                     
        System.assertEquals(0, retOAs2);
        Integer retOAs3 = [SELECT COUNT()  
                           FROM Opportunity_Assignment__c
                           WHERE Status__c = 'Duplicate'];
        System.debug('OpportunityAssignmentTriggerTest: Duplicate');
        System.assertEquals(1, retOAs3);
        System.debug('OpportunityAssignmentTriggerTest: testOpportunityAssignment FINISH');
    }
}