dxscale/core/Intacct/objects/CountryMapping__mdt/CountryMapping__mdt.object-meta.xml
<CustomObject>
    <label>Country Mapping</label>
    <pluralLabel>CountryMappings</pluralLabel>
</CustomObject>

dxscale/core/Intacct/objects/CountryProduct__mdt/CountryProduct__mdt.object-meta.xml
<CustomObject>
    <description>Mapping data between Country and Product CRM</description>
    <label>Country Product Mapping</label>
    <pluralLabel>Country Product Mappings</pluralLabel>
</CustomObject>

dxscale/core/Intacct/objects/CountryProduct__mdt/fields/CountryMapping__c.field-meta.xml
<CustomField>
    <fullName>CountryMapping__c</fullName>
    <description>Country mapping to determine product</description>
    <label>Country Mapping</label>
    <referenceTo>CountryMapping__mdt</referenceTo>
    <relationshipLabel>Country Product Mappings</relationshipLabel>
    <relationshipName>CountryProductMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/Intacct/objects/CountryProduct__mdt/fields/ProductMapping__c.field-meta.xml
<CustomField>
    <fullName>ProductMapping__c</fullName>
    <description>Corresponding product for the country</description>
    <label>Product Mapping</label>
    <referenceTo>ProductLocalCrmMapping__mdt</referenceTo>
    <relationshipLabel>Country Product Mappings</relationshipLabel>
    <relationshipName>CountryProductMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/Intacct/objects/ProductLocalCrmMapping__mdt/ProductLocalCrmMapping__mdt.object-meta.xml
<CustomObject>
    <description>Product to Local CRM mapping values</description>
    <label>Product Local CRM Mapping</label>
    <pluralLabel>Product Local CRM Mappings</pluralLabel>
</CustomObject>

dxscale/core/Intacct/objects/ProductLocalCrmMapping__mdt/fields/LocalCRMName__c.field-meta.xml
<CustomField>
    <fullName>LocalCRMName__c</fullName>
    <description>Field to hold mapped local CRM value for the product</description>
    <label>Local CRM Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

dxscale/core/Intacct/classes/ReferenceDataAccessHelper.cls
public class ReferenceDataAccessHelper {
    private static List<CountryProduct__mdt> productCrmMapping = null;
    /**
     * @description query to Product local crm mappings metadata type
     *
     * @return list of Product local crm mappings
     */
    public static List<CountryProduct__mdt> getProductCrmMapping() {
        if (productCrmMapping == null){
            productCrmMapping = [   SELECT  Id
                                        ,   MasterLabel
                                        ,   DeveloperName
                                        ,   Language
                                        ,   QualifiedApiName
                                        ,   NamespacePrefix
                                        ,   ProductMapping__r.MasterLabel
                                        ,   ProductMapping__r.LocalCRMName__c
                                        ,   CountryMapping__r.CountryCode__c
                                    FROM CountryProduct__mdt ];
        }

        return productCrmMapping;
    }

    /**
     * @description query to Product local crm mappings metadata type
     *
     * @return map of country code and map of product and local crm name
     */
    public static Map<String, Map<String, String>> getCrmMappingByProductByCountry() {
        // BUILD A MAP OF LOCAL CRM MAPPING BY PRODUCT BY COUNTRY
        Map<String, Map<String, String>> retVal = new Map<String, Map<String, String>>();

        for (CountryProduct__mdt eachMapping : ReferenceDataAccessHelper.getProductCrmMapping()) {
            retVal.put(eachMapping.CountryMapping__r.CountryCode__c
                    , new Map<String, String> { eachMapping.ProductMapping__r.MasterLabel => eachMapping.ProductMapping__r.LocalCRMName__c });
        }

        return retVal;
    }
}