dxscale/core/Intacct/objects/CountryMapping__mdt/CountryMapping__mdt.object-meta.xml
<CustomObject>
    <label>Country Mapping</label>
    <pluralLabel>CountryMappings</pluralLabel>
</CustomObject>

dxscale/core/Intacct/objects/CountryProduct__mdt/CountryProduct__mdt.object-meta.xml
<CustomObject>
    <description>Mapping data between Country and Product CRM</description>
    <label>Country Product Mapping</label>
    <pluralLabel>Country Product Mappings</pluralLabel>
</CustomObject>

dxscale/core/Intacct/objects/CountryProduct__mdt/fields/CountryMapping__c.field-meta.xml
<CustomField>
    <fullName>CountryMapping__c</fullName>
    <description>Country mapping to determine product</description>
    <label>Country Mapping</label>
    <referenceTo>CountryMapping__mdt</referenceTo>
    <relationshipLabel>Country Product Mappings</relationshipLabel>
    <relationshipName>CountryProductMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/Intacct/objects/CountryProduct__mdt/fields/ProductMapping__c.field-meta.xml
<CustomField>
    <fullName>ProductMapping__c</fullName>
    <description>Corresponding product for the country</description>
    <label>Product Mapping</label>
    <referenceTo>ProductLocalCrmMapping__mdt</referenceTo>
    <relationshipLabel>Country Product Mappings</relationshipLabel>
    <relationshipName>CountryProductMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

dxscale/core/Intacct/objects/ProductLocalCrmMapping__mdt/ProductLocalCrmMapping__mdt.object-meta.xml
<CustomObject>
    <description>Product to Local CRM mapping values</description>
    <label>Product Local CRM Mapping</label>
    <pluralLabel>Product Local CRM Mappings</pluralLabel>
</CustomObject>

dxscale/core/Intacct/objects/ProductLocalCrmMapping__mdt/fields/LocalCRMName__c.field-meta.xml
<CustomField>
    <fullName>LocalCRMName__c</fullName>
    <description>Field to hold mapped local CRM value for the product</description>
    <label>Local CRM Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

dxscale/core/Intacct/classes/ReferenceDataAccessHelper_Test.cls
@IsTest(SeeAllData = false)
public with sharing class ReferenceDataAccessHelper_Test {
    @IsTest static void getProductCrmMappingTest() {
        // GIVEN
        String countryCodeGB = 'GB';
        String countryCodeAUS = 'AU';
        // WHEN
        Test.startTest();
        List<CountryProduct__mdt> listProductCrmMapping = ReferenceDataAccessHelper.getProductCrmMapping();
        Test.stopTest();
        // THEN
        System.assert(listProductCrmMapping != null && !listProductCrmMapping.isEmpty());
        for (CountryProduct__mdt eachCountryProduct :listProductCrmMapping) {
            if (eachCountryProduct.CountryMapping__r.CountryCode__c != null) {
                if (eachCountryProduct.CountryMapping__r.CountryCode__c.equalsIgnoreCase(countryCodeGB)
                        || eachCountryProduct.CountryMapping__r.CountryCode__c.equalsIgnoreCase(countryCodeAUS)) {
                    System.assertEquals('INA - Intacct', eachCountryProduct.ProductMapping__r.LocalCRMName__c);
                }
            }
        }
    }

    @IsTest static void getCrmMappingByProductByCountryTest() {
        // GIVEN
        String countryCodeGB = 'GB';
        String countryCodeAUS = 'AU';
        String productName = 'Sage Intacct';
        // WHEN
        Test.startTest();
        Map<String, Map<String, String>> mapCountryProductCrm = ReferenceDataAccessHelper.getCrmMappingByProductByCountry();
        Test.stopTest();
        // THEN
        System.assert(mapCountryProductCrm != null && !mapCountryProductCrm.isEmpty());
        System.debug(mapCountryProductCrm);
        System.assert(mapCountryProductCrm.get(countryCodeAUS) != null);
        System.assert(mapCountryProductCrm.get(countryCodeGB) != null);
        System.assertEquals('INA - Intacct', mapCountryProductCrm.get(countryCodeGB).get(productName));
        System.assertEquals('INA - Intacct', mapCountryProductCrm.get(countryCodeAUS).get(productName));
    }
}