dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/PracticeEfficiencyReviewV2__c.object-meta.xml
<CustomObject>
    <description>UKIHARM-188: Practice Efficiency Review Version 2</description>
    <label>Practice Efficiency Review</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Review Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Efficiency Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <description>Automatically updates when the review automatically closes on 31st March and 30th September</description>
    <inlineHelpText>Automatically updates when the review automatically closes on 31st March and 30th September</inlineHelpText>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defaults to &apos;Open&apos; when new review created
Automatically updates to &apos;Closed&apos; on 31st March and 30th September&quot;</description>
    <inlineHelpText>Defaults to &apos;Open&apos; when new review created
Automatically updates to &apos;Closed&apos; on 31st March and 30th September&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/practiceEfficiencyReview/classes/PracticeEfficiencyReview_Batch.cls
global inherited sharing class PracticeEfficiencyReview_Batch implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator([
              SELECT Id, Status__c, ClosedDate__c, CreatedDate FROM PracticeEfficiencyReviewV2__c 
               WHERE ClosedDate__c = null
                 AND Status__c = 'Open'
        ]        
        );
    }
 
    global void execute(Database.BatchableContext BC, List<PracticeEfficiencyReviewV2__c> scope)
    {
       for(PracticeEfficiencyReviewV2__c r : scope){                   
          IF ((date.valueOf(r.CreatedDate) > date.newInstance(r.CreatedDate.year(), 01, 01)) &&  
              (date.valueOf(r.CreatedDate) <= date.newInstance(r.CreatedDate.year(), 03, 31))) 
          {
             r.Status__c = 'Closed';
             r.ClosedDate__c = date.newInstance(r.CreatedDate.year(), 03, 31);
          }ELSE IF ((date.valueOf(r.CreatedDate) > date.newInstance(r.CreatedDate.year(), 03, 31)) &&  
                    (date.valueOf(r.CreatedDate) <= date.newInstance(r.CreatedDate.year(), 09, 30)))
          {
             r.Status__c = 'Closed';
             r.ClosedDate__c = date.newInstance(r.CreatedDate.year(), 09, 30);     
          }ELSE{
             r.Status__c = 'Closed';
             r.ClosedDate__c =  date.newInstance(r.CreatedDate.year() + 1, 03, 31);
          }
       } 
       update scope;
    }  
    global void finish(Database.BatchableContext BC)
    {
    }
}