dxscale/sales/main/objects/OpportunityControlSwitch__c/OpportunityControlSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to control automations on the opportunity object</description>
    <label>Opportunity Control Switch</label>
</CustomObject>

dxscale/sales/main/objects/OpportunityControlSwitch__c/fields/RunTrigger__c.field-meta.xml
<CustomField>
    <fullName>RunTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to control the execution of validation rules on the opportunity object</description>
    <inlineHelpText>Checkbox to control the execution of validation rules on the opportunity object</inlineHelpText>
    <label>Run Trigger</label>
    <type>Checkbox</type>
</CustomField>

dxscale/sales/opportunityLineItem/classes/OpportunityLineItemTriggerHandler.cls
// Added under EAD-2102 to populate product names on the opportunity correctly
public inherited sharing class OpportunityLineItemTriggerHandler extends TriggerService {
    
    static String CLASSNAME = 'OpportunityLineItemTriggerHandler';
    
    public OpportunityLineItemTriggerHandler() {}

    public override void onAfterInsert() {
        LogControl.push('onAfterInsert', CLASSNAME);

        OpportunityControlSwitch__c triggerSwitch = OpportunityControlSwitch__c.getInstance();
        
        if (Test.isRunningTest() || triggerSwitch.RunTrigger__c ) {
        	OpportunityLineItemTriggerHelper.populateProductNamesOnOpportunity((List<OpportunityLineItem>) this.listNewSObject);
        }
    }
    
    public override void onAfterUpdate() {
        LogControl.push('onAfterUpdate', CLASSNAME);

        OpportunityControlSwitch__c triggerSwitch = OpportunityControlSwitch__c.getInstance();
        
        if (Test.isRunningTest() || triggerSwitch.RunTrigger__c ) {
        	OpportunityLineItemTriggerHelper.populateProductNamesOnOpportunity((List<OpportunityLineItem>) this.listNewSObject);
        }
    }

    public override void onAfterDelete() {
        LogControl.push('onAfterDelete', CLASSNAME);

        OpportunityControlSwitch__c triggerSwitch = OpportunityControlSwitch__c.getInstance();
        
        if (Test.isRunningTest() || triggerSwitch.RunTrigger__c ) {
        	OpportunityLineItemTriggerHelper.populateProductNamesOnOpportunity((List<OpportunityLineItem>) this.mapOldSObject.values());
        }
    }
}