dxscale/core/globalId/objects/Account/fields/Global_Id__c.field-meta.xml
<CustomField>
    <fullName>Global_Id__c</fullName>
    <description>This GAI which integrates with multiple systems to maintain the same value everywhere</description>
    <externalId>true</externalId>
    <label>Global Account Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

dxscale/core/globalId/objects/Contact/fields/Global_Id__c.field-meta.xml
<CustomField>
    <fullName>Global_Id__c</fullName>
    <description>This GAI which integrates with multiple systems to maintain the same value everywhere</description>
    <externalId>true</externalId>
    <label>Global Contact Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/PracticeEfficiencyReviewV2__c.object-meta.xml
<CustomObject>
    <description>UKIHARM-188: Practice Efficiency Review Version 2</description>
    <label>Practice Efficiency Review</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Review Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Efficiency Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <description>Populated from Account- Billing Address. Field to be stored in the back-end, to be used for Reporting</description>
    <inlineHelpText>Populated from Account- Billing Address. Field to be stored in the back-end, to be used for Reporting</inlineHelpText>
    <label>BillingCity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <description>Populated from Account- Billing Address. Field to be stored in the back-end, to be used for Reporting</description>
    <label>BillingCountry</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/BillingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingPostalCode__c</fullName>
    <description>Populated from Account- Billing Address. Field to be stored in the back-end, to be used for Reporting</description>
    <inlineHelpText>Populated from Account- Billing Address. Field to be stored in the back-end, to be used for Reporting</inlineHelpText>
    <label>BillingPostalCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/ClientName__c.field-meta.xml
<CustomField>
    <fullName>ClientName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Contact who conduct the survey</description>
    <inlineHelpText>The Contact who conduct the survey</inlineHelpText>
    <label>Client Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PracticeEfficiencyReviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/LocalCRMAccountID__c.field-meta.xml
<CustomField>
    <fullName>LocalCRMAccountID__c</fullName>
    <description>Pre-populated with the Local CRM Account ID from the Account</description>
    <inlineHelpText>Pre-populated with the Local CRM Account ID from the Account</inlineHelpText>
    <label>Local CRM Account ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/PracticeName__c.field-meta.xml
<CustomField>
    <fullName>PracticeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up an Account</description>
    <label>Practice Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PracticeEfficiencyReviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/objects/PracticeEfficiencyReviewV2__c/fields/ReviewTitle__c.field-meta.xml
<CustomField>
    <fullName>ReviewTitle__c</fullName>
    <description>Pre-populate the Review Title with the Account Name, the Year Half and the Financial Year</description>
    <inlineHelpText>Pre-populate the Review Title with the Account Name, the Year Half and the Financial Year</inlineHelpText>
    <label>Review Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

dxscale/sales/practiceEfficiencyReview/classes/PracticeEfficiencyReview_Helper_Test.cls
/**
 * @description  PracticeEfficiencyReview Helper Test
 * @author Betty Phan
 * @date 03/02/2021
 */
@IsTest
public class PracticeEfficiencyReview_Helper_Test {
    @IsTest
    static void testPopulateFieldsFromAccount() {
        Account acct = new Account(Name='Acc 1',Local_CRM_AccountID__c='PER-1234567890', BillingCity='Irvine', BillingCountry='United States', BillingPostalCode='92606',
                                    Phone='9999999', Global_Id__c=String.ValueOf(Math.round((Math.random() * (900000) + 100001))+Datetime.now().millisecond()));
        insert acct;
        Contact cont = new Contact(AccountId= acct.id, LastName='TestContact', Email = 'testuser@per.org',
                                   Global_Id__c=String.ValueOf(Math.round((Math.random() * (900000) + 200005))+Datetime.now().millisecond()));  
        insert cont;
        PracticeEfficiencyReviewV2__c per = new PracticeEfficiencyReviewV2__c( PracticeName__c = acct.id, ClientName__c = cont.id);
        insert per;      
        
        Test.startTest();        
        per = [SELECT ReviewTitle__c, LocalCRMAccountID__c, BillingCity__c, BillingCountry__c, BillingPostalCode__c from PracticeEfficiencyReviewV2__c where LocalCRMAccountID__c = 'PER-1234567890' LIMIT 1];  
        System.assert(per.BillingCity__c=='Irvine');
        System.assert(per.BillingCountry__c=='United States');
        System.assert(per.BillingPostalCode__c=='92606');      
        Test.stopTest();        
    }
}