dxscale/core/security/auth/objects/Auth_Credentials_Override__c/Auth_Credentials_Override__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Temporary overrides of auth credentials, useful for stubbing, testing in lower envs before prod.</description>
    <label>Auth Credentials Override</label>
</CustomObject>

dxscale/core/security/auth/objects/Auth_Credentials_Override__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <description>The endpoint to override</description>
    <inlineHelpText>The endpoint to override</inlineHelpText>
    <label>URL Endpoint</label>
    <type>TextArea</type>
</CustomField>

dxscale/core/security/auth/objects/Auth_Credentials_Override__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The Named credential name to use as override</description>
    <inlineHelpText>Allows you to override the authentication credentials</inlineHelpText>
    <label>Named Credential</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

dxscale/core/security/auth/objects/Auth_Credentials_Override__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>The scope you are now protecting</description>
    <inlineHelpText>Combined with other params allows you to change what is protected</inlineHelpText>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/AuthCredentials__mdt.object-meta.xml
<CustomObject>
    <description>Holds config to support creadential and external calls. things like basic HTTP or client grant (headless, system to system)</description>
    <label>AuthCredentials</label>
    <pluralLabel>AuthCredentials</pluralLabel>
</CustomObject>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Cache_Time_To_Live__c.field-meta.xml
<CustomField>
    <fullName>Cache_Time_To_Live__c</fullName>
    <description>The Time to live of the token in the Org level Platform Cache</description>
    <inlineHelpText>in seconds and should be slightly less than the grant expiry</inlineHelpText>
    <label>Cache Time To Live</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>if this call uses a named credential - name it here</description>
    <inlineHelpText>e.g. named credential name</inlineHelpText>
    <label>Named Credential</label>
    <type>TextArea</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Request_TimeOut__c.field-meta.xml
<CustomField>
    <fullName>Request_TimeOut__c</fullName>
    <description>Time in seconds before the request should fail</description>
    <inlineHelpText>in seconds </inlineHelpText>
    <label>Request Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Token_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_URL__c</fullName>
    <description>oAuth token URL</description>
    <inlineHelpText>e.g. https://login.microsoftonline.com/&lt;tennet&gt;/oauth2/v2.0/token</inlineHelpText>
    <label>Token URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

dxscale/core/security/auth/classes/BrokerConfigCredentials_Test.cls
@isTest
public class BrokerConfigCredentials_Test {

    @TestSetup
    static void makeData(){
        Auth_Credentials_Override__c authOverride = new Auth_Credentials_Override__c(Name='Test2',Named_Credential__c='OverrideName',
                            Scope__c='myOverriddenScope',Endpoint_URL__c='http://myoverride.com');
        insert authOverride;
    }
    
    @isTest
    static void testNoOverride(){
        AuthCredentials__mdt cred1 = new AuthCredentials__mdt(DeveloperName='Test1',
                    Token_URL__c='http://test.local.place.com',Named_Credential__c='RealName',Scope__c='myRealScope',Request_TimeOut__c=88);
        List<AuthCredentials__mdt> testAuthList = new List<AuthCredentials__mdt>();
        testAuthList.add(cred1);
        BrokerConfigCredentials config = new BrokerConfigCredentials();
        config.authList = testAuthList;
        IConfigCredentials credentials = config.getCredentials('Test1');
        System.assert(credentials != null);
        System.assertEquals(credentials.getURL(),'http://test.local.place.com');
        System.assertEquals(credentials.getNamedCredentialName(),'RealName');
        System.assertEquals(credentials.getScope(),'myRealScope');
        System.assertEquals(credentials.getRequestTimeOut(),88000);
    }

    @isTest
    static void testNoOverrideDefaultTimeOut(){
        AuthCredentials__mdt cred1 = new AuthCredentials__mdt(DeveloperName='Test1',
                    Token_URL__c='http://test.local.place.com',Named_Credential__c='RealName',Scope__c='myRealScope');
        List<AuthCredentials__mdt> testAuthList = new List<AuthCredentials__mdt>();
        testAuthList.add(cred1);
        BrokerConfigCredentials config = new BrokerConfigCredentials();
        config.authList = testAuthList;
        IConfigCredentials credentials = config.getCredentials('Test1');
        System.assert(credentials != null);
        System.assertEquals(credentials.getURL(),'http://test.local.place.com');
        System.assertEquals(credentials.getNamedCredentialName(),'RealName');
        System.assertEquals(credentials.getScope(),'myRealScope');
        System.assertEquals(credentials.getRequestTimeOut(),60000);
    }

    @isTest
    static void testWithOverride(){
        AuthCredentials__mdt cred1 = new AuthCredentials__mdt(DeveloperName='Test2',
                    Token_URL__c='http://test.local.place.com',Named_Credential__c='RealName',Scope__c='myRealScope', Request_TimeOut__c=100,Cache_Time_To_Live__c=3400);
        List<AuthCredentials__mdt> testAuthList = new List<AuthCredentials__mdt>();
        testAuthList.add(cred1);
        BrokerConfigCredentials config = new BrokerConfigCredentials();
        config.authList = testAuthList;
        IConfigCredentials credentials = config.getCredentials('Test2');
        System.assert(credentials != null);
        System.assertEquals(credentials.getURL(),'http://myoverride.com');
        System.assertEquals(credentials.getNamedCredentialName(),'OverrideName');
        System.assertEquals(credentials.getScope(),'myOverriddenScope');
    }    
}