dxscale/core/security/auth/objects/Auth_Credentials_Override__c/Auth_Credentials_Override__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Temporary overrides of auth credentials, useful for stubbing, testing in lower envs before prod.</description>
    <label>Auth Credentials Override</label>
</CustomObject>

dxscale/core/security/auth/objects/Auth_Credentials_Override__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <description>The endpoint to override</description>
    <inlineHelpText>The endpoint to override</inlineHelpText>
    <label>URL Endpoint</label>
    <type>TextArea</type>
</CustomField>

dxscale/core/security/auth/objects/Auth_Credentials_Override__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The Named credential name to use as override</description>
    <inlineHelpText>Allows you to override the authentication credentials</inlineHelpText>
    <label>Named Credential</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

dxscale/core/security/auth/objects/Auth_Credentials_Override__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>The scope you are now protecting</description>
    <inlineHelpText>Combined with other params allows you to change what is protected</inlineHelpText>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/AuthCredentials__mdt.object-meta.xml
<CustomObject>
    <description>Holds config to support creadential and external calls. things like basic HTTP or client grant (headless, system to system)</description>
    <label>AuthCredentials</label>
    <pluralLabel>AuthCredentials</pluralLabel>
</CustomObject>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Cache_Time_To_Live__c.field-meta.xml
<CustomField>
    <fullName>Cache_Time_To_Live__c</fullName>
    <description>The Time to live of the token in the Org level Platform Cache</description>
    <inlineHelpText>in seconds and should be slightly less than the grant expiry</inlineHelpText>
    <label>Cache Time To Live</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Client ID</description>
    <label>Client ID</label>
    <type>TextArea</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>client_secret</description>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <description>the oAuth grant type</description>
    <inlineHelpText>e.g. client_credentials</inlineHelpText>
    <label>Grant Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>if this call uses a named credential - name it here</description>
    <inlineHelpText>e.g. named credential name</inlineHelpText>
    <label>Named Credential</label>
    <type>TextArea</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/ProviderType__c.field-meta.xml
<CustomField>
    <fullName>ProviderType__c</fullName>
    <label>ProviderType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AzureAD</fullName>
                <default>true</default>
                <label>AzureAD</label>
            </value>
            <value>
                <fullName>Auth0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Request_TimeOut__c.field-meta.xml
<CustomField>
    <fullName>Request_TimeOut__c</fullName>
    <description>Time in seconds before the request should fail</description>
    <inlineHelpText>in seconds </inlineHelpText>
    <label>Request Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/security/auth/objects/AuthCredentials__mdt/fields/Token_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_URL__c</fullName>
    <description>oAuth token URL</description>
    <inlineHelpText>e.g. https://login.microsoftonline.com/&lt;tennet&gt;/oauth2/v2.0/token</inlineHelpText>
    <label>Token URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

dxscale/core/security/auth/classes/BrokerConfigCredentials.cls
public inherited sharing class BrokerConfigCredentials {
    

    private Map<String,IConfigCredentials> authMap;
    @TestVisible
    private List<AuthCredentials__mdt> authList;
    private Map<String,Auth_Credentials_Override__c> authOverrides;
    
    

    public BrokerConfigCredentials () {

    }

    private void init(){
        authMap = new Map<String,IConfigCredentials>();
        authOverrides = new Map<String,Auth_Credentials_Override__c>();

        List<Auth_Credentials_Override__c> overrides = [select Name,Named_Credential__c,Scope__c,Endpoint_URL__c from Auth_Credentials_Override__c];
        for(Auth_Credentials_Override__c auth:overrides){
            authOverrides.put(auth.Name,auth);
        }
        if(authList == null){
            authList = [select Token_URL__c,Named_Credential__c,Client_ID__c, Request_TimeOut__c,Client_Secret__c, Grant_Type__c,scope__c,Cache_Time_To_Live__c,ProviderType__c,DeveloperName FROM AuthCredentials__mdt];    
        }
        
        for(AuthCredentials__mdt auth:authList){
            //do we have an override ?
            Auth_Credentials_Override__c authOverride = authOverrides.get(auth.DeveloperName);
            core_ConfigCredentials cred = new core_ConfigCredentials(auth,authOverride);
            authMap.put(auth.DeveloperName,cred);
        }
    }

    public IConfigCredentials getCredentials(String credentialName){
        if(authMap == null){
            init();
        }
        return authMap.get(credentialName);
    }   



    
    public class core_ConfigCredentials implements IConfigCredentials{

        public String url;
        public Integer cacheTTL;
        public String clientID;
        public String clientSecret;
        public String type;
        public String providerType;
        //this is in milliseconds internally but held as seconds in the CMDT
        public Integer requestTimeOut;
        public String scope;
        public String namedCredentialName;        

        public core_ConfigCredentials(){}

        public core_ConfigCredentials(AuthCredentials__mdt auth, Auth_Credentials_Override__c ovd){
            this.url = auth.Token_URL__c;
            this.namedCredentialName = auth.Named_Credential__c;
            this.scope = auth.Scope__c;
            this.clientID = auth.Client_ID__c;
            this.clientSecret = auth.Client_Secret__c;
            this.providerType = auth.ProviderType__c;
            this.type = auth.Grant_Type__c;
            //default to 60 seconds
            Integer toMillis = 60000;
            if(auth.Request_TimeOut__c != null){
                toMillis = auth.Request_TimeOut__c.intValue()*1000;
            }
            this.requestTimeOut = toMillis;
            
            if(auth.Cache_Time_To_Live__c != null){
                this.cacheTTL = auth.Cache_Time_To_Live__c.intValue();
            }
            //load overrides if there are some
            if(ovd != null){
                //pull in overrides
                if(String.isNotBlank(ovd.Endpoint_URL__c)){
                    this.url = ovd.Endpoint_URL__c;
                }
                if(String.isNotBlank(ovd.Named_Credential__c)){
                    this.namedCredentialName = ovd.Named_Credential__c;
                }
                if(String.isNotBlank(ovd.Scope__c)){
                    this.scope = ovd.Scope__c;
                }
            }
        }



        public String getURL(){
            return this.url;

        }
        public Integer getCacheTTL(){
            return this.cacheTTL;
        }
        public String getClientID(){
            return this.clientID;
        }
        public String getClientSecret(){
            return this.clientSecret;
        }
        public String getType(){
            return this.type;
        }

        public String getNamedCredentialName(){
            return this.namedCredentialName;
        }
        
        public String getProviderType(){
            return this.providerType;
        }
        public Integer getRequestTimeOut(){
            return this.requestTimeOut;
        }
        public String getScope(){
            return this.scope;
        }
        
    }

}