dxscale/sales/callItems/objects/Call_Item__c/fields/Active_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Active_Start_Date__c</fullName>
    <label>Active Start Date</label>
    <type>Date</type>
</CustomField>

dxscale/sales/callItems/objects/Call_Item__c/fields/Target_Finish_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Finish_Date__c</fullName>
    <description>Date set by sales Opp to specify the end date of callitem JIRA-CCORE-1653</description>
    <label>Target Finish Date</label>
    <type>Date</type>
</CustomField>

dxscale/sales/callItems/objects/Call_Item__c/fields/Visibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Status__c</fullName>
    <label>Visibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dxscale/sales/callItems/objects/CallitemBatchJobSettings__mdt/CallitemBatchJobSettings__mdt.object-meta.xml
<CustomObject>
    <description>Setting  to store details of  Email to be send on call item scheduled jobs completion.</description>
    <label>CallitemBatchJobSettings</label>
    <pluralLabel>CallitemBatchJobSettings</pluralLabel>
</CustomObject>

dxscale/sales/callItems/classes/callItemActiveDeactivateBatch.cls
global class callItemActiveDeactivateBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    // callItemsProcessed to retain state across transactions
    global Integer CallItemsList4Updatesize = 0;
    global Integer CallItemsupdateSucess = 0;
    global Integer CallItemsupdateFailure = 0;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, Visibility_Status__c, Active_Start_Date__c, Target_Finish_Date__c ' +
            ' FROM Call_Item__c ' + 
            'Where (Active_Start_Date__c <= TODAY AND Visibility_Status__c = \'Inactive\')'+
            ' OR (Target_Finish_Date__c <= TODAY AND Visibility_Status__c = \'Active\')'
            
        );
    }
    global void execute(Database.BatchableContext bc, List<Call_Item__c> ci){
        // process each batch of records
        
        List<Call_Item__c> CallItemsList4Update = new List<Call_Item__c>();
        Boolean Flag;
        for(Call_Item__c c : ci){
            
            Flag =false;            
          
            if(flag ==false && c.Active_Start_Date__c == c.Target_Finish_Date__c && c.Active_Start_Date__c == date.TODAY() && (c.Visibility_Status__c != 'Inactive'||c.Visibility_Status__c != ''||c.Visibility_Status__c != NULL)) {
                c.Visibility_Status__c = 'Inactive';
                CallItemsList4Update.add(c);
                flag =true;                
            }
            
            if(flag ==false && c.Active_Start_Date__c <= date.TODAY()&& c.Target_Finish_Date__c > date.TODAY() && c.Visibility_Status__c != 'Active') {
                c.Visibility_Status__c = 'Active';
                CallItemsList4Update.add(c);
                flag =true;
            }
            if(flag ==false && c.Target_Finish_Date__c <= date.TODAY() && c.Visibility_Status__c != 'Inactive') {
                c.Visibility_Status__c = 'Inactive';
                CallItemsList4Update.add(c);
                flag =true;
            }
           
            //update CallItemsList4Update;
            
      
        }  
        Database.SaveResult[] srList = Database.update(CallItemsList4Update, false);
              System.debug(CallItemsList4Update + ' CallItemsList4Update');
        CallItemsList4Updatesize = CallItemsList4Update.size();
            
            // Iterate through each returned result
    for (Database.SaveResult sr : srList) {
       if (sr.isSuccess()) {
        // Operation was successful, so get the ID of the record that was processed
              CallItemsupdateSucess++;
              System.debug('Successfully updated Call item. Call item ID: ' + sr.getId());
                               }
      else {
        // Operation failed, so get all errors                
        for(Database.Error err : sr.getErrors()) {
               CallItemsupdateFailure++; 
               System.debug('The following error has occurred.');                    
               System.debug(err.getStatusCode() + ': ' + err.getMessage());
               System.debug('Call item fields that affected this error: ' + err.getFields());
                                }
           }
           
        }
    }
    
    global void finish(Database.BatchableContext bc){
           
        CallitemBatchJobSettings__mdt Emaildata =[select Emails__c from CallitemBatchJobSettings__mdt where DeveloperName='Email_details'];
        
        String status = 'Success';
        if (CallItemsupdateFailure!=0)
        {Status = 'Failure';}        
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = Emaildata.Emails__c.split(',');
        mail.setToAddresses(toAddresses);
        mail.setSubject('Call Item Batch '+ Status);
        mail.setPlainTextBody('Total callItems Processed -> '+ CallItemsList4Updatesize+ ' with '+
                               CallItemsupdateSucess+ ' -> Updated Successfully '+
                               CallItemsupdateFailure+' -> with failures.');
       if(!Test.isRunningTest()){
           Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });}
        
    }    
}