dxscale/sales/callItems/objects/Call_Item__c/fields/Attempted_Calls__c.field-meta.xml
<CustomField>
    <fullName>Attempted_Calls__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Automatically counts comes from CTI 
JIRA-CCORE-1653</description>
    <label>Attempted Calls</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/sales/callItems/objects/Call_Item__c/fields/isOpenedByOwner__c.field-meta.xml
<CustomField>
    <fullName>isOpenedByOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatically checks this box when user opens the callitem  JIRA-CCORE-1653</description>
    <label>is Opened By Owner</label>
    <type>Checkbox</type>
</CustomField>

dxscale/sales/callItems/classes/CallItemActivityCountLTCtrl.cls
public inherited sharing class CallItemActivityCountLTCtrl {
	static final String CLASSNAME = 'CallItemActivityCountLTCtrl';

	@AuraEnabled
	public static void callCounter(Id recordId) {
		LogControl.push('callCounter', CLASSNAME);

		try {
			Call_Item__c callItem = [
				SELECT Id, OwnerId, isOpenedByOwner__c, Attempted_Calls__c
				FROM Call_Item__c
				WHERE Id = :recordId
				WITH SECURITY_ENFORCED
				LIMIT 1
			];

			if (
				UserInfo.getUserId() == callItem.OwnerId &&
				callItem.isOpenedByOwner__c != true &&
				Schema.sObjectType.Call_Item__c.fields.isOpenedByOwner__c.isupdateable()
			) {
				callItem.isOpenedByOwner__c = true;
				Database.update(callItem);
			}
		} catch (Exception e) {
			LogControl.debugException(e);
		} finally {
			LogControl.pop();
		}
	}
}