dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/Service_Framework_Audit__c.object-meta.xml
<CustomObject>
    <description>Audited messages from the Services Framework</description>
    <label>Service Framework Audit</label>
    <nameField>
        <displayFormat>SFA-{00000000}</displayFormat>
        <label>Service Framework Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Framework Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Input_Data__c.field-meta.xml
<CustomField>
    <fullName>Input_Data__c</fullName>
    <description>Input Data for an Service Invocation</description>
    <inlineHelpText>Input Data for an Service Invocation</inlineHelpText>
    <label>Input Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Details__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Details__c</fullName>
    <description>Invocation Details for a Service Invocation</description>
    <inlineHelpText>Invocation Details for a Service Invocation</inlineHelpText>
    <label>Invocation Details</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Name__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Name__c</fullName>
    <description>Name fo the invocation that trigger the audited service</description>
    <inlineHelpText>Name fo the invocation that trigger the audited service</inlineHelpText>
    <label>Invocation Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Output_Data__c.field-meta.xml
<CustomField>
    <fullName>Output_Data__c</fullName>
    <description>Output Data for an Service Invocation</description>
    <inlineHelpText>Output Data for an Service Invocation</inlineHelpText>
    <label>Output Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/actions/classes/AuditRepublish.cls
global with sharing class AuditRepublish {

    public class ScreenData {
        @AuraEnabled public String state;
        @AuraEnabled public String errorMessage;
        @AuraEnabled public String returnMessage;
    }


    @AuraEnabled
    public static ScreenData rerun (Id recordId, String inputMessage) {
        Service_Framework_Audit__c sfa = 
        [select Invocation_Details__c,Invocation_Name__c 
            from Service_Framework_Audit__c
            where id = :recordId];
        
        ServiceInvocation sinv = ServiceInvocation.initialize(sfa.Invocation_Name__c);        
        IInvocation_Details invocationDetails = (IInvocation_Details) Service.deserializeInvocationDetails (sfa.Invocation_Details__c);        
        IService_Input_Master isi = Service.deserializeInput(inputMessage, invocationDetails);                

        IService_Output_Master outputData = sinv.invokeService(isi);
        // store the State
        String outputState = outputData.getState();

        // start to populate the intended output
        ScreenData sd = new ScreenData(); 
        sd.state = outputState;
        sd.returnMessage = 'Successfully republished';

        if (outputState != 'SUCCESS') {
            sd.returnMessage = outputData.getErrorMessage();
        }        
        return sd;
    }

    @AuraEnabled
    public static String getInput (Id recordId) {
        String inputDate;
        List<String> fieldList = new List<String>{'Input_Data__c','Output_Data__c','Invocation_Details__c','Invocation_Name__c'};
        Boolean hasPermission = PermissionUtils.checkFieldPermissions(fieldList,'Service_Framework_Audit__c',PermissionUtils.PERMISSION_TYPE.READ_PERMISSION);
        if(hasPermission){
            Service_Framework_Audit__c sfa = [select Input_Data__c,Output_Data__c,Invocation_Details__c,Invocation_Name__c from Service_Framework_Audit__c where id = :recordId];
            inputDate = sfa.Input_Data__c;
        }
        
        return inputDate;
    }

    


}