dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/Service_Framework_Audit__c.object-meta.xml
<CustomObject>
    <description>Audited messages from the Services Framework</description>
    <label>Service Framework Audit</label>
    <nameField>
        <displayFormat>SFA-{00000000}</displayFormat>
        <label>Service Framework Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Framework Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <description>If interacting with external systems, track the supplied correlation id to track through salesforce</description>
    <externalId>true</externalId>
    <label>Correlation Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Data_Status__c.field-meta.xml
<CustomField>
    <fullName>Data_Status__c</fullName>
    <description>Data Status of the returned output, for example if the data is real or stubbed</description>
    <inlineHelpText>Data Status of the returned output, for example if the data is real or stubbed</inlineHelpText>
    <label>Data Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Service Durationn in milliseconds. This is the time that the service runs for, in the case of an async invocation this does not include any enqueued time but is the time that the service method takes to run</description>
    <inlineHelpText>Service Durationn in milliseconds. This is the time that the service runs for, in the case of an async invocation this does not include any enqueued time but is the time that the service method takes to run</inlineHelpText>
    <label>Service Duration (ms)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Service returned Error Message</description>
    <inlineHelpText>Service returned Error Message</inlineHelpText>
    <label>Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Implementing_Class__c.field-meta.xml
<CustomField>
    <fullName>Implementing_Class__c</fullName>
    <description>Implementing Class that ran the service</description>
    <inlineHelpText>Implementing Class that ran the service</inlineHelpText>
    <label>Implementing Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Input_Data__c.field-meta.xml
<CustomField>
    <fullName>Input_Data__c</fullName>
    <description>Input Data for an Service Invocation</description>
    <inlineHelpText>Input Data for an Service Invocation</inlineHelpText>
    <label>Input Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Details__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Details__c</fullName>
    <description>Invocation Details for a Service Invocation</description>
    <inlineHelpText>Invocation Details for a Service Invocation</inlineHelpText>
    <label>Invocation Details</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Duration__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Duration__c</fullName>
    <description>Duration of the service invocation. For asynchronous calls this is the duration from the invocation until the service is invoked, i.e. it includes any enqueued time waiting for the service to run</description>
    <inlineHelpText>Duration of the service invocation. For asynchronous calls this is the duration from the invocation until the service is invoked, i.e. it includes any enqueued time waiting for the service to run</inlineHelpText>
    <label>Invocation Duration (ms)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Name__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Name__c</fullName>
    <description>Name fo the invocation that trigger the audited service</description>
    <inlineHelpText>Name fo the invocation that trigger the audited service</inlineHelpText>
    <label>Invocation Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Time__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Time__c</fullName>
    <description>Timestamp for the initial invocation call</description>
    <inlineHelpText>Timestamp for the initial invocation call</inlineHelpText>
    <label>Invocation Time</label>
    <type>DateTime</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Type__c</fullName>
    <description>Invocation Type of the Audited invocation</description>
    <inlineHelpText>Invocation Type of the Audited invocation</inlineHelpText>
    <label>Invocation Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Iteration__c.field-meta.xml
<CustomField>
    <fullName>Iteration__c</fullName>
    <description>Iteration that was triggered</description>
    <inlineHelpText>Iteration that was triggered</inlineHelpText>
    <label>Iteration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Method on the Service that was invoked</description>
    <inlineHelpText>Method on the Service that was invoked</inlineHelpText>
    <label>Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Output_Data__c.field-meta.xml
<CustomField>
    <fullName>Output_Data__c</fullName>
    <description>Output Data for an Service Invocation</description>
    <inlineHelpText>Output Data for an Service Invocation</inlineHelpText>
    <label>Output Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Time__c</fullName>
    <description>Time that the Service completed its processing</description>
    <inlineHelpText>Time that the Service completed its processing</inlineHelpText>
    <label>Response Time</label>
    <type>DateTime</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <description>Name of the Service that was invoked</description>
    <inlineHelpText>Name of the Service that was invoked</inlineHelpText>
    <label>Service Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Service_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Start_Time__c</fullName>
    <description>Time the service starts to run. For an async invocation this is after the service call is dequeued from the Platform Event</description>
    <inlineHelpText>Time the service starts to run. For an async invocation this is after the service call is dequeued from the Platform Event</inlineHelpText>
    <label>Service Start Time</label>
    <type>DateTime</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Service return state</description>
    <inlineHelpText>Service return state</inlineHelpText>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/methods/audit/implementations/AuditService_Version_1/classes/AuditServiceV1.cls
public inherited sharing class AuditServiceV1 implements IService_Implementation {
 
    public IStringOutput dispatch(IInvocation_Details invocationDetails, IService_Input_Master inputData) {
        IService_Audit isi = (IService_Audit) inputData;
        return implementationBody(invocationDetails, isi);
    }

    @TestVisible private IStringOutput implementationBody(IInvocation_Details invocationDetails, IService_Audit isi) {       

        System.debug('AuditServiceV1');

        IStringOutput iso = new StringOutputV1();
        iso.setOutputMessage('Audit Message Posted');
        iso.setState('SUCCESS');
        iso.setDataStatus('Real');

        Service_Framework_Audit__c tl = new Service_Framework_Audit__c();
        tl.Input_Data__c = isi.getInputData();
        tl.Output_Data__c = isi.getOutputData();
        tl.Invocation_Details__c = isi.getInvocationDetails();
        tl.State__c =  extractState(isi.getState());
        tl.Error_Message__c =  isi.getErrorMessage();
        tl.Invocation_Type__c =  isi.getInvocationType();
        tl.Data_Status__c =  isi.getDataStatus();
        tl.Duration__c =  isi.getServiceDuration();
        tl.Service_Start_Time__c =  isi.getServiceStartTime();
        tl.Response_Time__c =  isi.getResponseTime();
        tl.Invocation_Time__c =  isi.getInvocationTime();
        tl.Invocation_Duration__c =  isi.getInvocationDuration();
        tl.Correlation_Id__c = isi.getCorrelationId();

        isi.parseInvocationDetails();
        tl.Implementing_Class__c = isi.getImplementingClass();
        tl.Service_Name__c = isi.getServiceName();
        tl.Iteration__c = isi.getIteration();
        tl.Method__c = isi.getMethod();
        tl.Invocation_Name__c = isi.getInvocationName();
        insert tl;

        return iso;
    }

    @TestVisible private static String extractState(String rawState) {
        return rawState.contains('FAIL') ? 'FAILURE' : 'SUCCESS';
    }

}