dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/Service_Framework_Audit__c.object-meta.xml
<CustomObject>
    <description>Audited messages from the Services Framework</description>
    <label>Service Framework Audit</label>
    <nameField>
        <displayFormat>SFA-{00000000}</displayFormat>
        <label>Service Framework Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Framework Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Input_Data__c.field-meta.xml
<CustomField>
    <fullName>Input_Data__c</fullName>
    <description>Input Data for an Service Invocation</description>
    <inlineHelpText>Input Data for an Service Invocation</inlineHelpText>
    <label>Input Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/objects/Service_Framework_Audit__c/fields/Invocation_Name__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Name__c</fullName>
    <description>Name fo the invocation that trigger the audited service</description>
    <inlineHelpText>Name fo the invocation that trigger the audited service</inlineHelpText>
    <label>Invocation Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dxscale/core/services/AuditService/entities/Service_Framework_Audit__c/actions/classes/AuditRepublish_Test.cls
@isTest
public class AuditRepublish_Test {
   

    @TestSetup
    static void makeData(){
        User adminUser = CoreTestUtils.setUpUserWithPermissions('myAdmOrg','System Administrator',new String[]{'auditService'});
        User userNoPerms = CoreTestUtils.setUpUserWithPermissions('myStdOrg','Standard User',new List<String>());
        Service_Framework_Audit__c audit1 = new Service_Framework_Audit__c(Input_Data__c='{"hello":"world"}',Invocation_Name__c='TestInvocation1');
        insert audit1;
    }

    @isTest
    static void testGetInput(){
        User adminUser = [select Id from user where email like '%@myAdmOrg.com' limit 1];
        User stdUser = [select Id from user where email like '%@myStdOrg.com' limit 1];        
        Service_Framework_Audit__c audit = [select Id from Service_Framework_Audit__c LIMIT 1];
        Test.startTest();
            System.runAs(stdUser){
                String inputData = AuditRepublish.getInput(audit.Id);
                System.assert(inputData == null,'expected Not to have permissions');
            }
            System.runAs(adminUser){
                String inputData = AuditRepublish.getInput(audit.Id);
                System.assert(inputData != null,'expected to to have permissions');
            }            
        Test.stopTest();        
    
    }

}